### PR TITLE
Pre-render Mermaid diagrams

### PR DESCRIPTION
**Pull request by astrojuanlu**
## Description

This avoids calling the Mermaid CLI every single time we build the docs. The Mermaid diagrams change very rarely, so this is unwarranted. Plus it was creating lots of problems, see gh-3395 for the last straw.

## Development notes

Unfortunately, this means that, next time we change the diagrams, we'd have to re-render them. That can be done by calling the Mermaid CLI ourselves or using any other service though, so this shouldn't be a problem.

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Diagrams:

- https://kedro--3449.org.readthedocs.build/en/3449/get_started/new_project.html#flowchart-of-general-choice-of-tools
- https://kedro--3449.org.readthedocs.build/en/3449/starters/new_project_tools.html#flowchart-of-example-choice-of-tools-and-example-selections
- https://kedro--3449.org.readthedocs.build/en/3449/deployment/index.html#deployment
- https://kedro--3449.org.readthedocs.build/en/3449/deployment/databricks/index.html#databricks

**Review by stichbury — CHANGES_REQUESTED** [review]
Yay! This is great. Thank you.

Could you also leave a comment above each diagram on how to make an update and regenerate the PNG please? That is, what did you do this time to build them, so the rest of the team know how to uncomment, where to put the code, etc etc.

**Comment by astrojuanlu** [comment]
Wrote the instructions in https://github.com/kedro-org/kedro/wiki/Render-Mermaid-diagrams, tested them locally, and adding links from within the docs. Let me know what you think @stichbury

**Review by stichbury — APPROVED** [review]
Looks great to me. I'd maybe later include versioning of what you're using mermaid/Python etc but I see it's kind of listed there already in the npm install

Thanks for this!

**Review by merelcht — APPROVED** [review]
Thanks @astrojuanlu this makes sense to me 👍

**Pull request merged**
