### PR TITLE
Update `kedro new` prompts

### PR DESCRIPTION
**Pull request by AhdraMeraliQB**
Replacement for https://github.com/kedro-org/kedro/pull/3355

> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description

Fixes part of #3054:
- Switch order of prompts - 1. name 2. addons 3. example
- Adjust copy at the selection step will be updated to mention the benefits of using "software engineering best practice"

[Link to new copy](https://github.com/kedro-org/kedro/issues/3054#issuecomment-1775659975)

I believe this PR also addresses #3341 

Question: The updated copy has no mention of any message for the case where an example pipeline isn't selected. Should we add one? Also should we be leveraging colour anywhere?

## Development notes
name and add-ons take default values, example pipeline is selected (yes)
Previous flow:
image

Updated flow (as of [6a8b1e4](https://github.com/kedro-org/kedro/pull/3358/commits/6a8b1e4c9bf2b43358d0975b3613528793c518d4)):
image

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [x] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by merelcht — APPROVED** [review]
LGTM 👍

**Comment by stichbury** [comment]
Looks great, thank you!

**Review by stichbury — APPROVED** [review]

**Review by ankatiyar — APPROVED** [review]

**Comment by amandakys** [comment]
Might be a nit but the new line between the project name and project add ons section is gone in the new flow image. 
re: colours: It would be nice to put the --flag examples in colour to give them a discovery boost i'm not sure how that works with people's theme colours and i have no preference of colour. Giving the addon names a separate colour would also be nice.

**Comment by AhdraMeraliQB** [comment]
> Might be a nit but the new line between the project name and project add ons section is gone in the new flow image. re: colours: It would be nice to put the --flag examples in colour to give them a discovery boost i'm not sure how that works with people's theme colours and i have no preference of colour. Giving the addon names a separate colour would also be nice.

The new line seems to be a one-off from pre-emptive value entry on my side, I've been unable to recreate it when following the prompts

I've used green for the colour as we had used that previously for the directory line. I think if we highlight the add-ons we should also highlight the line "It has been created with an example pipeline." - what do you think?

Here's what this would look like:
image

**Review by amandakys — APPROVED** [review]

**Pull request merged**
