### PR TITLE
Release notes changes for 18.4 

### PR DESCRIPTION
**Pull request by stichbury**
This PR adds a section to describe docs changes for the 18.4 release to RELEASE.md.

We could use the open PR and branch for other changes as we make them for the release, but equally happy just to get this signed off and merged so it's ready for liftoff 🚀 

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/2064"></a>

### CODE REVIEW

**Review by merelcht — APPROVED** [review]
So many great doc changes in this release!! 👏

**Review by noklam — APPROVED** [review]
🚀

**Comment by stichbury** [comment]
> Additionally, do we want to call out @noklam's work to fix the sticky headers?

Definitely. Added.

**Comment by noklam** [comment]
I vaguely remember in earlier releases notes we used to have a section thanks for contributor, particularly the open source one. Should we tag them too?

**Comment by noklam** [comment]
I vaguely remember in earlier releases notes we used to have a section thanks for contributor, particularly the open source one. Should we tag them too?

**Comment by stichbury** [comment]
> I vaguely remember in earlier releases notes we used to have a section thanks for contributor, particularly the open source one. Should we tag them too?

Nice idea! And @merelcht has kindly given me a[ list of OS contributions](https://github.com/kedro-org/kedro/issues/2050#issuecomment-1326513789), which makes it easier. We can acknowledge the team by linking to the docs FAQ so don't have to name ourselves unless we want to.

**Comment by merelcht** [comment]
> I vaguely remember in earlier releases notes we used to have a section thanks for contributor, particularly the open source one. Should we tag them too?

Yes we did. I think we stopped doing it because we very frequently had to ask people to add in their names and sometimes that would block the merging of the PR. On the repo you can see everyone who has contributed so we just left it at that.

**Comment by noklam** [comment]
Instead of adding their name, maybe it is enough to use their GitHub handle?

**Comment by stichbury** [comment]
* [jstammers](https://github.com/jstammers)
* [FlorianGD](https://github.com/FlorianGD)
* [yash6318](https://github.com/yash6318)
* [carlaprv](https://github.com/carlaprv)
*

**Pull request merged**
