### PR TITLE
Update the project template with black==22.1.0

### LINKED ISSUE #1327: Update black to a non pre-release version (black==22.1.0)
## Description

The kedro template still use [``black==21.5b1``](https://github.com/kedro-org/kedro/blob/b573594bf1b1df8f73f345673db3a0224df0a634/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/requirements.txt#L1) which is a pre-release version non covered by [the stability policy](https://black.readthedocs.io/en/latest/the_black_code_style/index.html#stability-policy) of the last [22.1.0 version](https://github.com/psf/black/releases/tag/22.1.0).

## Context

I would like to be able to install a non prelease version of black and to benefit for their stability policy. I also think it is better for kedro not to rely on a pre-release version if an official release is available (e.g. to avoid warning from internal security tools).

## Possible Implementation

- Change to ``black==22.1.0`` in the template requirements
- Update the files of the template with the new black version (a couples of files have some lines splitted differently). This is completely straightforward.

Unless I miss something which would have some other impact, I can open a PR.

## Possible Alternatives

Let people change the black version themselves in their templates. Since click was upgraded in #1193 , this will be possible in ``kedro=0.18``. I do not really like this option (you have to remember to do this each time you start a kedro project + you have a first commit with pure formatting change which is less readable) but this would be a possible workaround.

### PR DESCRIPTION
**Pull request by Galileo-Galilei**
## Description

Close #1327 

## Development notes

- Update black version in features/steps and templates/project
- I did NOT update black version in kedro iteself because it leads to modifying a lot of files in the core library, which is allegedly something I won't be allowed to.
- I run black on the template to check it won't be modified, is there an existing test for that?
 - As discussed in above issue, this version of black needs click>=8.0, so it goes in develop
 - Weirdly, the RELEASE.md does not have a "Bug fixes and other changes" section, so I added this change in "Major features and improvements"
 
## Checklist

- [X] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [X] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/1331"></a>

### CODE REVIEW

**Comment by datajoely** [comment]
Hi @Galileo-Galilei  I think  we may be able to go to click 1.0+ since we merged support for click 8 (https://github.com/kedro-org/kedro/pull/1260/files) a week ago. @lorenabalan is this right?

**Comment by datajoely** [comment]
but most importantly @Galileo-Galilei  thank you! forgot to say that in the first message!

**Comment by Galileo-Galilei** [comment]
Hi @datajoely, sorry I don't understand what you want me to do with click? I know you updated click on the develop branch, because I open the issue after I encountered some conflicts... with this black version 😄, that's why I open the PR on the develop branch.

**Comment by datajoely** [comment]
@Galileo-Galilei I was being silly - I wrote `click 1.0+` when I meant `black 1.0+` 🙈

**Review by MerelTheisenQB — APPROVED** [review]
Thanks for this @Galileo-Galilei 😄 ⭐

**Comment by Galileo-Galilei** [comment]
Thanks for the review @MerelTheisenQB. Some comments:
- I've rebased to merge conflicts in README and sign off all commits
- I've changed ``black==22.1.0`` to ``black~=22.0`` to match [black stability policy](https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy) which guarantee no formatting change with this setup and is more flexible. Is it what you meant with ``black 1.0+`` @datajoely ?

**Review by idanov — APPROVED** [review]
Thanks for fixing this 🎉 I think we should update black for Kedro as well (maybe not just before the release, but after 0.18).

**Pull request merged**
