### PR TITLE
Update docs font family to Inter and swap the logo

### PR DESCRIPTION
**Pull request by tynandebold**
## Description

This PR aligns the documentation font with the rebrand guidelines. It will also update the logo.

[Here's a RTD deploy demo](https://kedro--2611.org.readthedocs.build/en/2611/).

## Development notes

Swapped the Google font.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by stichbury** [comment]
Does the font in the sidebar look a bit too bigly?

image

**Comment by stichbury** [comment]
I can't really tell but I wonder if the sidebar font could be slightly smaller to match the main font size, if it is bigger (could just be an effect of extra whitespace)

**Comment by Mackay031** [comment]
Hi @tynandebold. Logos can be found here:

https://mckinsey.box.com/s/vgbfn1ouwac7kzen9lzesfizshq7dug6

As far as font sizes, see attached. I have used same Typescale as website. Havent shown equivalent in rems. Also, lets use the logo variants as in this screenshot. Thanks :)

Kedro doc_1

**Comment by stichbury** [comment]
Wow, this looks so good now. Thanks 🙏

**Review by stichbury — APPROVED** [review]

**Comment by astrojuanlu** [comment]
Rendered docs: https://kedro--2611.org.readthedocs.build/en/2611/

**Review by astrojuanlu — APPROVED** [review]
This looks so sharp 🔥

**Comment by Huongg** [comment]
thanks @astrojuanlu for updating the Kedro text. One more thing I need to fix is the font-family. Can't seem to get the custom font-family built in the RTD :( it should be "Inter" instead of "Titillium"

**Comment by astrojuanlu** [comment]
Weird @Huongg , it looks just fine for me 🤔 

image

And there are no more mentions of Titilium in the `kedro` repository that I can find. Maybe some caching thing?

**Comment by Huongg** [comment]
ah yeah very strange @astrojuanlu , maybe caching as it does have inter font if i open it in incognito mode....but not in my normal browser

**Pull request merged**
