### PR TITLE
Update the tutorial of "Visualise pipelines"

### PR DESCRIPTION
**Pull request by dinotuku**
## Description
I found some small things that could be changed when following the tutorial.

## Development notes
- Change three `.csv` files (`preprocessed_companies.csv`, `preprocessed_shuttles.csv`, `model_input_table.csv`) to parquet files (`preprocessed_companies.pq`, `preprocessed_shuttles.pq`, `model_input_table.pq`) so that they matched how they were specified in the previous article ([Create a pipeline -> Persist pre-processed data](https://kedro.readthedocs.io/en/latest/tutorial/create_pipelines.html#persist-pre-processed-data) and [Create a pipeline -> Persist the model input table](https://kedro.readthedocs.io/en/latest/tutorial/create_pipelines.html#persist-the-model-input-table))
- Change the corresponding data types from `pandas.CSVDataSet` to `pandas.ParquetDataSet`
- Add a missing import, `import plotly.graph_objs as go`, for the example using `plotly.JSONDataSet`
- Add a note for installing seaborn in case it is not yet installed (This line is from the later tutorial page, [Set up experiment tracking -> View and compare plot data](https://github.com/kedro-org/kedro/blob/ff8e2a1dd22422655344216b54d225ec869ac4c7/docs/source/tutorial/set_up_experiment_tracking.md#view-and-compare-plot-data))

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/1913"></a>

### CODE REVIEW

**Comment by noklam** [comment]
@dinotuku Thank you for flagging this, it does look like an inconsistency to me, you may also want to update the dataset as a parquet dataset in this case.

**Comment by dinotuku** [comment]
> @dinotuku Thank you for flagging this, it does look like an inconsistency to me, you may also want to update the dataset as a parquet dataset in this case.

Thanks! I will update it with a new commit.

**Comment by dinotuku** [comment]
For some reason, this link (https://github.com/Raalsky) is broken (500 Server Error: Internal Server Error) 😕

**Review by MerelTheisenQB — APPROVED** [review]
Great catch! 🦅 Thanks for your contribution! 😄

**Review by noklam — APPROVED** [review]
thank you for catching this!

**Pull request merged**
