### PR TITLE
Replace Pipeline with modular_pipeline.pipeline

### LINKED ISSUE #1833: Replace Pipeline with pipeline across all tests
## Description
Currently, `Pipeline` is used to instantiate objects of this class across the testing code base. This should be updated to use the `pipeline` factory in `kedro.pipeline.modular_pipeline`.

## Context
This comes from @AntonyMilneQB's comment on #1795 suggesting that these changes be made for the test files modified for that feature.

### PR DESCRIPTION
**Pull request by adamfrly**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description

Replace all instaces to kedro.pipeline.Pipeline in the test codebase with modular_pipeline.pipeline.

Resolves #1833 

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [x] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [x] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/2189"></a>

### CODE REVIEW

**Comment by adamfrly** [comment]
Two builds were started, one had the `win_e2e_tests-3.10` step fail and the other had the `win_unit_tests-3.8` step fail. In both builds, the other step succeeded. They both seem to be errors in things not related to my changes, but that might just be my inexperience talking (e.g. `win_unit_tests-3.8` failed due to a "non-existent" powershell cmdlet). Not sure where to proceed from here, any advice would be greatly appreciated.

**Comment by jmholzer** [comment]
> Two builds were started, one had the `win_e2e_tests-3.10` step fail and the other had the `win_unit_tests-3.8` step fail. In both builds, the other step succeeded.

Don't worry, it's nothing you did. The Windows CI can be temperamental, in these cases we just re-run from the failed step :).

**Comment by jmholzer** [comment]
Great work getting all tests and the signature check to pass! :D

At the moment, there are quite a few unrelated changes in the PR, this can sometimes happen when rebasing.

The solution is to do another interactive rebase (process explained [here](https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-a-pull-request)), dropping the commits you didn't author.

Let me know if you'd like help with this :).

**Comment by adamfrly** [comment]
@jmholzer I think I've properly rebased and removed the unrelated commits. Let me know if there's anything I missed

**Review by jmholzer — COMMENTED** [review]
Awesome, thanks for the PR, appreciate your work on this 😃.

I've been thinking about the strategy of binding the name `modular_pipeline` to `pipeline`.

There are two things I like about it:

1. It is a more descriptive name than `pipeline`, which makes the tests easier to understand.
2. It conveniently avoids the trouble of shadow naming variables already named `pipeline` in a clean way.

The downside is:
1. It is currently inconsistent with other tests, where `pipeline` is imported and used without binding another name.

What do you think @merelcht?

**Comment by merelcht** [comment]
> The downside is:
> 
> 1. It is currently inconsistent with other tests, where `pipeline` is imported and used without binding another name.
> 
> What do you think @merelcht?

This isn't true though is it? I did a search in the code base and the only file that still has `pipeline` imported as before is the the `tests_spark_dataset.py` which @adamfrly mentioned not changing.

**Comment by merelcht** [comment]
This looks good, thanks for taking this up @adamfrly 😄 Can you add the change to the release notes? (It's not really a user facing change, but good to have this in our change records)

btw, would you mind making the same change in the tests on `kedro-datasets`? https://github.com/kedro-org/kedro-plugins/tree/main/kedro-datasets

**Comment by adamfrly** [comment]
@merelcht Yeah I'll add it to the release notes now, and yeah I'll open up a PR for similar changes in https://github.com/kedro-org/kedro-plugins/tree/main/kedro-datasets. Thanks for the help both of you 😄

**Comment by jmholzer** [comment]
> This isn't true though is it? I did a search in the code base and the only file that still has `pipeline` imported as before is the the `tests_spark_dataset.py` which @adamfrly mentioned not changing.

We currently have one instance of `pipelline` being used in `tests/runner/test_sequential_pipeline.py`. This was added in https://github.com/kedro-org/kedro/pull/1795/commits/ffb4074c33b1a4cc9db7dd0b2e2c8130dffd7379.

@adamfrly, would you mind changing the use of `pipeline` in that file to your approach 🙂? Should be a quick fix, though let me know if you'd like my help.

**Comment by adamfrly** [comment]
> We currently have one instance of `pipelline` being used in `tests/runner/test_sequential_pipeline.py`. This was added in [ffb4074](https://github.com/kedro-org/kedro/commit/ffb4074c33b1a4cc9db7dd0b2e2c8130dffd7379).
> 
> @adamfrly, would you mind changing the use of `pipeline` in that file to your approach 🙂? Should be a quick fix, though let me know if you'd like my help.

@jmholzer My understanding is that we'd want to replace any instance in the tests where `kedro.pipeline.modular_pipeline.pipeline` is being imported, but not being bound to the name `modular_pipeline`. I don't think this happens anywhere else in the tests.

In `tests/runner/test_sequential_pipeline.py`, the `kedro.pipeline.pipeline` object is being imported, not  `kedro.pipeline.modular_pipeline.pipeline` which in my understanding means nothing needs changing. That is unless you also wish for me to replace all instances of `kedro.pipeline.pipeline` on top of replacing `kedro.pipeline.Pipeline`

**Comment by adamfrly** [comment]
@jmholzer I see, thanks for the explanation :). I've made changes to `tests/runner/test_sequential_pipeline.py` accordingly.

**Comment by adamfrly** [comment]
I was also able to figure out what was going wrong in my local env so I was able to add the spark related changes!

**Review by jmholzer — APPROVED** [review]
Awesome, thanks @adamfrly ✅.

Congratulations on your first PR! 🎉 Great work 🙂

**Comment by adamfrly** [comment]
Thanks for your help, very happy to be able to contribute! 🥳

**Review by merelcht — APPROVED** [review]
Thanks for the contribution @adamfrly ⭐ 🎉

**Pull request merged**
