### PR TITLE
Update docs css to point to shared location #3205

### PR DESCRIPTION
**Pull request by stichbury**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description
Mirrors changes in Viz docs

## Development notes
Removed CSS files and pointed to S3 location. Added code for meganav

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by stichbury** [comment]
Preview is here: https://kedro--3206.org.readthedocs.build/en/3206/

**Comment by stephkaiser** [comment]
This is currently what the documentation looks like on desktop and mobile:
Screenshot 2023-10-31 at 14 04 23
Screenshot 2023-10-31 at 12 38 15
Screenshot 2023-10-31 at 12 38 23

The desktop version is fine (just need to make sure the nav is consistent when the user clicks on a navigation item). The mobile version needs more work, as you can see above the mobile menu interaction is a little strange.

I've created a quick design mockup below to illustrate expectations for mobile. Designs [here](https://www.figma.com/file/3kSpvIO1veLKfy9qHxuXwF/Kedro-WIP?type=design&node-id=806-31385&mode=design&t=4W8bK1UxUN9Tnnhw-4).

**Changes proposed for mobile:**
- update logo and menu icon
- check font sizes and weights
- include breadcrumb
- fix mobile menu 
  - menu icon location, close button icon
  - menu full width
  - logo position
  - navigation items in menu (Kedro, Kedro-Viz, Kedro-Datasets)

Docs - Wireframe v1-MobileLanding
Docs - Wireframe v1-MobileMenu

---

**Additional changes for desktop (only if easy to change as further docs redesign will come later):**
- reduce logo size
- navigation items positioning
- navigation items active-state cell size
- navigation items active-state cell colour (change orange to black)
- navigation items hover-state cell colour
- reduce size of breadcrumb

Docs - Wireframe v1-Desktop


If changing the active-state colour from orange to black is too much effort, here is the orange version below. Please make sure the colour is the same across mobile as well.

Docs - Desktop-Orange

**Comment by stichbury** [comment]
This is great, thank you!

@vladimir-mck This is feedback for you and feel free to work on this branch.

**Comment by stichbury** [comment]
I'm not massively happy about adding a Kedro logo SVG file to the `docs/source` folder. If it isn't already, it should be on the https://github.com/kedro-org/kedro-brand-identity repo and referenced from there so it can be reused across the docs subprojects as needed.

**Comment by stephkaiser** [comment]
thank you for this @vladimir-mck! its looking really great - some design QA comments below:

1. Navigation items font weight - doesn't look like Semi-Bold, it looks like Regular at the moment or Light (same on mobile)
Screenshot 2023-11-07 at 18 31 41

2. Mobile menu scrolling - menu items and search bar should not be fixed for this version, enable full scrolling please. 
3. Kedro, Kedro-Viz, and Kedro-Datasets cells have more side padding compared to desktop version (compare with above screenshot), can we make them the same please?
Screenshot 2023-11-07 at 18 37 16

4. Are we able to show breadcrumb on mobile as well?
5. Are we able to reduce size of breadcrumb on desktop?

6. Close menu icon is too thin, please use the icon from designs. I've attached it below and can also send it via Slack. 
PNG - IconShell-Close
SVG - IconShell-Close
Screenshot 2023-11-07 at 18 39 38

7. Left contents panel scrollbar - can we move it so it's aligned next to the divider line?
Screenshot 2023-11-07 at 18 41 53

**Comment by stichbury** [comment]
Closing this as it's done and merged in a separate PR

**Pull request closed without merging**
