### PR TITLE
Add Spark Databricks dataset

### PR DESCRIPTION
**Pull request by tiencuongkieu**
## Description
Add Spark Databricks/or Table Dataset as discussed in here https://github.com/quantumblacklabs/kedro/issues/974

## Development notes
Add a new file `kedro/extras/datasets/spark/spark_databricks_dataset.py`. 
TODO: This is a draft PR only. Will need to add test as well. 

## Checklist

- [x] Read the [contributing](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md) file
- [ ] Added tests to cover my changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by SajidAlamQB** [comment]
@tiencuongkieu Do you want to continue working on this PR?

**Comment by tiencuongkieu** [comment]
> 

Hi Sajid. I would like to finish this PR but were busy with client work the last few months. I think i can resume the work from next week.

**Comment by tiencuongkieu** [comment]
> Hi @tiencuongkieu, just checking if you'd still like to continue with this PR? It's been open for a while, so it's very out of date with the current `main` and you might run into issues merging. The team is more than happy to support, so do shout if you need assistance completing this work.

Hi @MerelTheisenQB @datajoely Sorry for this super super delay. It is still difficult for me to find proper time to work on this PR. Really appreciate if someone can pick this up and continue the work. As you mentioned, the branch is already out of sync with the main so much, so it shouldn't be delayed more.

**Comment by MerelTheisenQB** [comment]
I'm closing this PR for now as there's currently no capacity to work on this. Anyone who is interested to implement a Spark Databricks dataset is more than welcome to open a PR.

**Pull request closed without merging**
