### PR TITLE
Remove Deprecated development  CLI

### LINKED ISSUE #1617: Remove development related CLI commands
Following the research conducted in https://github.com/kedro-org/kedro/issues/1293 it has been decided that the following commands will all be deprecated and removed:

1. `kedro jupyter convert`
2. `kedro activate-nbstripout`
3. `kedro build-docs`
4. `kedro build-reqs`
5. `kedro lint`
6. `kedro test`

Remove all the above commands from Kedro on `develop`, this also includes updating documentation that mentions any of the above commands. 

The template project should still be linted and `pytest` should run on it, so some of these calls (e.g. in e2e tests) need to be replaced with the underlying calls, e.g. `pytest`.

This will be released in Kedro `0.19.0`

### PR DESCRIPTION
**Pull request by noklam**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description

Close #1617 

- [ ] `kedro jupyter convert`
- [ ]  `kedro activate-nbstripout`
- [ ] `kedro build-docs`
- [ ] `kedro build-reqs`
- [ ]  `kedro lint`
- [ ] `kedro test`

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by merelcht — COMMENTED** [review]
Don't forget to also remove mentions of these commands from the docs.

**Comment by noklam** [comment]
@stichbury I removed most of the section related to the CLI, for 1 or 2 smaller version I have keep them around but remove the reference to CLI.

**Review by merelcht — APPROVED** [review]
🥳

**Review by astrojuanlu — APPROVED** [review]
Let's goooooo

**Pull request merged**
