### PR TITLE
Seems like the rename from class_obj to dataset_type wasn't complete

### PR DESCRIPTION
**Pull request by merelcht**
## Description
While working with datasets and using an environment where I had the kedro develop version installed I ran into an issue: "UnboundLocalError: cannot access local variable 'class_obj' where it is not associated with a value" 

I think this happened because the rename done from `class_obj` to `dataset_type` in https://github.com/kedro-org/kedro/pull/3272 wasn't completely finished.  

## Development notes
Renamed all occurrences of `class_obj` in `parse_dataset_definition` to `dataset_type`.

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by astrojuanlu — APPROVED** [review]

**Review by noklam — COMMENTED** [review]
Do you have a case that I can reproduce the error? I am surprised no tests catch the error. 

This may be a bug for an edge case, `class_obj` was refactor into two different variables `class_obj` and `dataset_type`, so it's not just a rename.

I can't see clearly what's the bug now but I think I could fix this with an example.

**Comment by merelcht** [comment]
> Do you have a case that I can reproduce the error? I am surprised no tests catch the error.
> 
> This may be a bug for an edge case, `class_obj` was refactor into two different variables `class_obj` and `dataset_type`, so it's not just a rename. At some point `class_obj` is just `str` but then get recast as an object, so the refactoring keep them separately to make this clear.
> 
> I am probably missing an `if` somewhere but I can't see it clearly. It should be an easy fix if I have an example.

@noklam I found the issue when I was running the dataset tests against the `develop` branch.

**Comment by noklam** [comment]
Close in favor of #3400

**Comment by merelcht** [comment]
Closing in favour of #3400

**Pull request closed without merging**
