### PR TITLE
Add pip-compile workflow to Github Actions

### PR DESCRIPTION
**Pull request by ankatiyar**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description

Continuing the move to Github Actions - also port the `pip-compile` tests for linux + windows. 

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by astrojuanlu — APPROVED** [review]
Looks good to me 👍🏽 

What's the plan for the CircleCI jobs? I recall a comment yesterday somewhere but can't find it

**Comment by ankatiyar** [comment]
> Looks good to me 👍🏽
> 
> What's the plan for the CircleCI jobs? I recall a comment yesterday somewhere but can't find it

@astrojuanlu I've added the develop branch to the workflows here as well. 
I think we're planning to keep the CircleCI jobs running for a while and then remove them after everything is ported and running smoothly like we did for `kedro-plugins`.

**Review by merelcht — APPROVED** [review]
LGTM! 👍

**Review by SajidAlamQB — APPROVED** [review]
Thank you @ankatiyar!

**Pull request merged**
