### PR TITLE
Fixing issues 2607 redundant packages

### PR DESCRIPTION
**Pull request by laizaparizotto**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by noklam** [comment]
Not sure about this, the import looks necessary to me, how does it work for `DryRunner(AbstractRunner)` if we are not importing it?

**Comment by deepyaman** [comment]
> Not sure about this, the import looks necessary to me, how does it work for `DryRunner(AbstractRunner)` if we are not importing it?
> 
> See[ my response ](https://github.com/kedro-org/kedro/issues/2607#issuecomment-1562911899)in the OG issue
> 
> > @opensean Hey! Thank you for spotting this, would you be open to creating a PR to fix this? I also did a quick check the import is not strictly needed, but they are there for type hints. Could you double check?

@noklam I think it's just duplicated?

image

**Comment by noklam** [comment]
@deepyaman my bad, should have check the whole file😐

**Review by noklam — APPROVED** [review]
Thanks!

**Pull request merged**
