### PR TITLE
Update the DryRunner doc to make it more useful

### LINKED ISSUE #1997: Dry run option that checks DAG and existence of pipeline inputs
## Description
Hello, I would like to use something like this dry runner https://kedro.readthedocs.io/en/stable/nodes_and_pipelines/run_a_pipeline.html#custom-runners but in a slightly different context - I would like to also check whether the data exists.
I am using multiple kedro environments https://kedro.readthedocs.io/en/stable/kedro_project_setup/configuration.html for different model experiments
When I do a partial run with `--from-nodes` and `--to-nodes` (to save time over a full pipeline run), I often discover that some data does not exist in my environment - but it takes a while to discover this, as the code needs to run first
Then "checking whether the data exists" is a bit complex:
- Either check whether it is an intermediate output of the provided pipeline
- Or check whether it can be read from the catalog using the _exists method of the abstract dataset class

## Context
This would save considerable time in debugging pipeline runs.

## Possible Implementation
I shared a rough, unpolished implementation in this slack thread: https://kedro-org.slack.com/archives/C03RKP2LW64/p1667314369586859
Improvements:
- Using public `exists` method
- Raising the appropriate data not existing error

### PR DESCRIPTION
**Pull request by noklam**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description

Close #1997 
I worked with this user previously and created a more useful DryRunner.

We can decide later whether we want to include this officially in `kedro` but we can change our doc first before that happens.
See 
* #2310 

## Development notes

The `DryRunner` is more powerful now as it checks whether the underlying data exists and surface the error early. Previously if you have a long pipeline the error will not show up until the node is executed and you can have `FileNotFoundError`. The DryRunner wouldn't load the data so it's fast, it only use the `exists` method to make sure such data exist in the path.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by stichbury — APPROVED** [review]
LGTM, thanks! I take it that we don't have this as code anywhere, so the docstring you've fixed doesn't also need to be changed within some Python somewhere?

**Comment by noklam** [comment]
@stichbury Thanks! Correct, at the moment it's just an example in our doc, #2310 is the ticket to decide whether we should include it in the Python package.

**Comment by astrojuanlu** [comment]
Rendered version: https://kedro--2460.org.readthedocs.build/en/2460/nodes_and_pipelines/run_a_pipeline.html#custom-runners

**Review by merelcht — APPROVED** [review]
Thanks @noklam! This looks good 👍

**Comment by noklam** [comment]
Thank you @jwaton for suggesting this initially. :)

**Pull request merged**
