### PR TITLE
Update Kedro Team list

### PR DESCRIPTION
**Pull request by noklam**
## Description
Part of the onboarding process. :)

## Development notes
To add myself to the team list.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [x] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [x] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/1353"></a>

### CODE REVIEW

**Review by lorenabalan — APPROVED** [review]
Awesome! 🎉 You'll probably have to re-run the linkcheck build.

**Comment by noklam** [comment]
Not sure what's going on here, the "build_docs_only" job is still "In Progress", but when I click inside the job everything show "success".

**Review by MerelTheisenQB — APPROVED** [review]
🎉 🎉 🎉

**Comment by noklam** [comment]
Oh my, i just noticed that I make this PR from my fork PR lol.

**Pull request merged**
