### PR TITLE
[DRAFT] Docs mega nav 

### PR DESCRIPTION
**Pull request by vladimir-mck**
## Description
This PR was created as a first step to creating a global navigation for docs as per #3024 

## Development notes
- Pull the branch
- Build and & start the docs

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by datajoely** [comment]
No comment other than rad PR title

**Comment by stichbury** [comment]
This is great, thanks @vladimir-mck!

Built docs are here for people wanting a preview: https://kedro--3168.org.readthedocs.build/en/3168/#

We won't need the "Deployment" section for now -- only Framework, Viz and Datasets (all titles TBD)

**Comment by stichbury** [comment]
@vladimir-mck I've changed the base branch to `develop` as we are working over there now.

**Comment by vladimir-mck** [comment]
Closing this PR, it will be handled with [this one](https://github.com/kedro-org/kedro/pull/3206)

**Comment by vladimir-mck** [comment]
Closing this PR, it will be handled with [this one](https://github.com/kedro-org/kedro/pull/3206)

**Pull request closed without merging**
