### PR TITLE
Update Kedro banner image

### PR DESCRIPTION
**Pull request by tynandebold**
## Description

Resolves https://github.com/kedro-org/kedro-viz/issues/1393.

## QA notes

Here's the README local to this branch: https://github.com/kedro-org/kedro/tree/chore/update-banner-images.

We've also got a light and dark theme banner working, per [this article](https://dev.to/mateusabelli/make-images-responsive-to-lightdark-mode-on-github-3gbg) Yetu found.

Can confirm it's working on the dark theme!

image

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by merelcht — APPROVED** [review]
👍

**Comment by stichbury** [comment]
Sorry to be a numpty @tynandebold but how do I get to see the dark theme? I'm looking at https://docs.kedro.org/en/latest/index.html with the dark theme on my Mac but still see the light docs.

image

**Comment by tynandebold** [comment]
Ah ok. The dark/light theme is only for the GitHub README, not RTD. I should've been more clear.

I don't think we have this capability right now in RTD.

**Comment by astrojuanlu** [comment]
sphinx_rtd_theme does not have a dark theme https://github.com/readthedocs/sphinx_rtd_theme/issues/224 hopefully will get fixed after we switch to a newer baseline #2394

**Comment by stichbury** [comment]
Perfect, thanks both. I may promote this in the next "In the Pipeline" as a new feature, just wanted to be sure what was possible.

**Pull request merged**
