### PR TITLE
Remove logic to define layer at the top level from DataCatalog

### PR DESCRIPTION
**Pull request by lrcouto**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description

 
Removes the logic used to to define the layer attribute at top-level within the DataCatalog class.

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by AhdraMeraliQB** [comment]
@lrcouto If I remember correctly, we should actually be able to remove the `layers` attribute (L293) as a whole 🤔 

CC: @merelcht to confirm

**Comment by merelcht** [comment]
> @lrcouto If I remember correctly, we should actually be able to remove the `layers` attribute (L293) as a whole 🤔
> 
> CC: @merelcht to confirm
> 
> Edit: Also don't forget to add these changes to `RELEASE.md` 😄

Yes true! We can remove `layer`/`layers` everywhere now it will be passed through `metadata` instead.

**Review by merelcht — COMMENTED** [review]
See @AhdraMeraliQB's comment, this also means we can delete some of the tests.

**Review by AhdraMeraliQB — COMMENTED** [review]
`test_factory_layer` on line 961 of the test file can also go, as well as any mention of `catalog.layers` (which shouldn't be passing anyway... weird)

Can't highlight the specific lines in the review as they haven't been changed 😬

**Review by noklam — APPROVED** [review]
Thanks for the PR! I think we should add one more line to `Breaking changes to the API`.

**Review by merelcht — APPROVED** [review]
Agree with @noklam on the release note, but otherwise LGTM 👍

**Pull request merged**
