### PR TITLE
Document integration with DVC 

### PR DESCRIPTION
**Pull request by JaynouOliver**
## Description
Fixes - #2691 
Creating a polished and accurate document might require a deeper understanding of both Kedro and DVC , as well as potentially developing a plugin to facilitate this integration, as mentioned earlier. 

Require more guidance regarding this, happy to make further changes and learn about this

## Development notes

Created a new file for Integration with DVC. Further changes required in the future, also require contribution of a plugin.

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [X] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Hi @JaynouOliver, RTD is failing with

```
sphinx.errors.SphinxWarning: /home/docs/checkouts/readthedocs.org/user_builds/kedro/checkouts/3261/docs/source/integrations/dvc_integration.md:document isn't included in any toctree
```

Could you please fix it? @stichbury not sure where in the current information architecture should we place it.

**Comment by JaynouOliver** [comment]
sure, I will try to get back with the changes in my MORNING time

**Comment by astrojuanlu** [comment]
Also could you please signoff your commit so the DCO check passes? If you click on it you will find instructions. If it was only one commit you can do `git commit --amend --signoff --no-edit`, if you had more, `git rebase --signoff`. After rewriting the history you will need to do `git push --force`.

And if you keep working on this branch, please use the `-s/--signoff` flag when committing, for example `git commit -s -m 'Add feature'`.

**Comment by JaynouOliver** [comment]
Absolutely, I will do it from the next time I make any kind of changes, thanks a lot for the help

**Comment by JaynouOliver** [comment]
I have been working on it, need some more time

**Comment by JaynouOliver** [comment]
I am not able to find the TOC

**Comment by stichbury** [comment]
> I am not able to find the TOC

I suggest for now that we put this in the `Development` section of the docs. So you need to add your file to https://github.com/kedro-org/kedro/blob/main/docs/source/development/index.md for it to build.

**Comment by JaynouOliver** [comment]
thanks, working on it

**Comment by astrojuanlu** [comment]
Rendered result: https://kedro--3261.org.readthedocs.build/en/3261/integrations/dvc_integration.html

**Comment by astrojuanlu** [comment]
Hi @JaynouOliver , the docs finally render but the page is a bit barebones. The end result should more or less be "the steps you would have loved to have before you started", hence they need to be more specific, have a clear goal in mind, and end with a working Kedro + DVC installation.

We can provide help with specific questions but we don't have the resources to write this page on your behalf. I'm marking the PR as draft for now, let us know when it's ready for a first review.

**Comment by JaynouOliver** [comment]
I wanted to learn more about how to do this, need some guidance

**Comment by stichbury** [comment]
> I wanted to learn more about how to do this, need some guidance

Hi @JaynouOliver!
As @astrojuanlu mentions, we don't have the resources to write the page but would advise you to look at our existing docs, particularly those on development (IDEs), deployment and PySpark integration, if you're interested in how we describe how to interact with tools and services. We are happy to review your efforts and improve on things; at present there's not really enough to review but I hope this is sufficiently to get you started towards a solid draft we can edit together.

**Comment by JaynouOliver** [comment]
sure, I will try from my end

**Comment by stichbury** [comment]
I am going to close this PR for now. We can reopen it if you have more documentation to contribute @JaynouOliver and thank you again for your contribution.

**Comment by JaynouOliver** [comment]
Thanks. Will do

**Pull request closed without merging**
