### PR TITLE
Feature/api dataset load args

### PR DESCRIPTION
**Pull request by lucasjamar**
## Description
In response to https://github.com/kedro-org/kedro/issues/711

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/1445"></a>

### CODE REVIEW

**Comment by datajoely** [comment]
I like this! Would you mind adding a unit test?

**Comment by AntonyMilneQB** [comment]
Should we move all the other optional arguments like `data`, `method`, etc. inside `load_args` also? This would be a breaking change so need to go in develop (and we can keep your PR going to main). `url` should stay top-level though.

This would make for a more consistent interface and be tidier I think, but interested in hearing what others think. Maybe there's a good reason those arguments are more important than others passed to `load_args` and belong at top-level?

**Comment by MerelTheisenQB** [comment]
Hi @lucasjamar, are you still interested in completing this PR? Let the team know if you need any help! 🙂

**Comment by MerelTheisenQB** [comment]
> @MerelTheisenQB . Im sorry but i really cant find the time to do this properly. I wold be happy if someone can take this over and get the cicd checks to pass. Sorry

Thanks for the update @lucasjamar and no worries. We'll add it to our backlog and also welcome other contributors to take over if they have capacity.

**Comment by AntonyMilneQB** [comment]
Superseded by #1633. Thanks @lucasjamar for your initial work for this!

**Pull request closed without merging**
