### PR TITLE
Test approach to giving more descriptive dataset load/save error messages

### PR DESCRIPTION
**Pull request by datajoely**
Signed-off-by: @datajoely joel.schwarzmann@quantumblack.com

## Description

[Discord user](https://discord.com/channels/778216384475693066/932754976990695465/932760413815312444) highlighted that dataset exceptions can be very opaque. If load/save fails it falls back to the `AbstractDataSet` implementation in `core.py` and returns a message like follows:
```
kedro.io.core.DataSetError: Failed while saving data to data set CustomDataSet(filepath=/my_path/filepath.csv, load_args={}, protocol=file, save_args={'index': False}, version=Version(load=None, save='2022-01-17T21.51.04.634Z')).
list expected at most 1 argument, got 2
```

In this situation the `TypeError` from passing multiple errors to the `list` constructor is hidden as well as the actual line and location for where the save method is implemented.

This PR attempts to add in the relevant part of the exception call stack so this information is available to the user when debugging. 

## Development notes

Added private method to `core.py` which retrieves the traceback from the exception and returns the 2nd, 3rd and 4th elements in the call stack to help users debug. The 1st element of the call stack is the abstract class in `core.py` and thus not relevant.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/1164"></a>

### CODE REVIEW

**Comment by datajoely** [comment]
This is what the current output looks like:
image

**Comment by datajoely** [comment]
Closing as I think 3.10 support will solve this somewhat

**Comment by datajoely** [comment]
Reopening as an open source user reported this error:

image

...but it turned out the underlying issue was that the correct dependency wasn't instaleld.

**Comment by datajoely** [comment]
Confirming if the user was running < 0.17.5 as this may have been fixed already

**Comment by MerelTheisenQB** [comment]
Hi @datajoely, what is the status of this PR? Do you need the team to review?

**Comment by datajoely** [comment]
Ah sorry I thought I closed it!

**Pull request closed without merging**
