### PR TITLE
Remove type comment in favor of PEP 526 for variable annotation 

### PR DESCRIPTION
**Pull request by merelcht**
## Description
Addresses https://github.com/kedro-org/kedro/issues/2078

## Development notes
The problem found in #2078 was caused by the following: https://github.com/PyCQA/pyflakes/issues/747#issuecomment-1326939923 Essentially, `flake8` doesn't support type checking in comments anymore with the `# type: ...` syntax. Instead it now looks for the PEP 526 syntax for variable annotation: https://peps.python.org/pep-0526/

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by astrojuanlu — COMMENTED** [review]
Thanks @merelcht! I was always a fan of `type: ` comments, I guess Python is solidly heading towards types as annotations...

Some questions:

- What's the role of `flake8` in typing? Does it replace MyPy, or it only checks that the annotations are correct?
- May I suggest using `import typing as t`? (Silly personal preference, but I think it's nice to avoid polluting the global namespace with typing stuff, and instead I prefer to do `t.Any`, `t.TypedDict` and such)
- May I suggest adding `from __future__ import annotations` to leverage [PEP 585](https://peps.python.org/pep-0585/) and hence be able to do `list[str]` instead of `t.List[str]`? (Available from Python 3.7)
- Where it makes sense for this PR (without having to overhaul the whole codebase) may I suggest using `str | None` instead of `Optional[str]` and `str | bytes` instead of `Union[str, bytes]`?

**Comment by astrojuanlu** [comment]
I see, thanks! Okay with keeping `from typing import *`, I had to try 😸 

About PEP 604, I'm not sure, it's not clearly written in the PEP 🤔

**Comment by merelcht** [comment]
I'll create a new PR to leverage [PEP 585](https://peps.python.org/pep-0585/).

**Review by astrojuanlu — APPROVED** [review]
LGTM!

**Review by noklam — APPROVED** [review]
Looks good to me!

**Pull request merged**
