### PR TITLE
Add option to raise errors during `find_pipelines`

### LINKED ISSUE #2910: Provide option to raise error explicitly for `find_pipelines`
## Description

`find_pipelines` is added since 0.18.3 as a pipeline autodiscovery feature. While this is useful, it is sometimes hard to debug because it raises warning but not error so the program will keep running.

## Context

For library developers, they may need strict control and want the pipeline fails explicitly. This features was designed for development, so any half-developed pipeline won't prevent other pipeline from running (incomplete pipeline, not installed library etc)

Some quotes from users:
> We recently have users reporting issues when running tensorflow on M1. The error was hidden in some kedro pipelines and it took a while to dig out the root cause from the user. In general, it can be difficult to predict when and where we will encounter these issue. Therefore, we are planning to build some CI workflows for checking our packages and pipelines for M1 machines in general.

> I'm noticing that warnings like SyntaxErrors and type errors are considered "warnings" by Kedro, which continues to try to run the pipeline.  Is there a setting to escalate these to Errors so they can abort the pipeline run?
  [15 days ago](https://kedro-org.slack.com/archives/C03RKP2LW64/p1690226861464369?thread_ts=1690222660.057049&cid=C03RKP2LW64)
Is there a way to mark a pipeline as a work in progress and then tell find_pipelines to error on warnings?  Or is the answer to just not use pipeline autodiscovery

### PR DESCRIPTION
**Pull request by deepyaman**
## Description
Resolves #2910 

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by noklam — COMMENTED** [review]
Implementation wise looks fine. I think we should update the relevant documentation as well. I was wondering should we also update the starter to add the default to make this more discoverable.

```python
pipelines = find_pipelines(raise_errors=False)
```

**Comment by deepyaman** [comment]
> Implementation wise looks fine. I think we should update the relevant documentation as well. I was wondering should we also update the starter to add the default to make this more discoverable.
> 
> ```python
> pipelines = find_pipelines(raise_errors=False)
> ```

Good point! See [71e0f64](https://github.com/kedro-org/kedro/pull/3823/commits/71e0f64f038929f4d127cbc9f092217894187592) for documentation added in response.

**Review by ElenaKhaustova — COMMENTED** [review]
The implementation looks good to me!

My only question is whether we should keep the default value `raise_errors=False` rather than `raise_errors=True`. If I understood correctly, the feature was initially designed for developers, so any half-developed pipeline won't prevent another pipeline from running. However, general users find debugging hard if an issue occurs and the pipeline is still running. So we may consider making `raise_errors=True` the default behaviour, as the chance that developers are aware of this feature and the flag is higher than that of general users.

**Comment by deepyaman** [comment]
> My only question is whether we should keep the default value `raise_errors=False` rather than `raise_errors=True`. If I understood correctly, the feature was initially designed for developers, so any half-developed pipeline won't prevent another pipeline from running. However, general users find debugging hard if an issue occurs and the pipeline is still running. So we may consider making `raise_errors=True` the default behaviour, as the chance that developers are aware of this feature and the flag is higher than that of general users.

I'm OK with that, if that's the prevailing user feedback. @astrojuanlu @merelcht any opinion?

Also, I don't personally feel that behavior change is "breaking" (it's pretty easy to update your registry, and hopefully you're not running with a broken pipeline already in production), but would be happy to get others' view.

**Comment by merelcht** [comment]
> > My only question is whether we should keep the default value `raise_errors=False` rather than `raise_errors=True`. If I understood correctly, the feature was initially designed for developers, so any half-developed pipeline won't prevent another pipeline from running. However, general users find debugging hard if an issue occurs and the pipeline is still running. So we may consider making `raise_errors=True` the default behaviour, as the chance that developers are aware of this feature and the flag is higher than that of general users.
> 
> I'm OK with that, if that's the prevailing user feedback. @astrojuanlu @merelcht any opinion?
> 
> Also, I don't personally feel that behavior change is "breaking" (it's pretty easy to update your registry, and hopefully you're not running with a broken pipeline already in production), but would be happy to get others' view.

I think it's a good call to make the default `raise_errors=True`. We have indeed heard that users struggle with debugging, so raising errors explicitly by default will hopefully help.

**Comment by astrojuanlu** [comment]
Without a full understanding of https://github.com/kedro-org/kedro/issues/2401, I'd be wary of setting `raise_errors=True` on a micro release. We want to take a broader look at what kind of errors people find while debugging.

My recommendation would be to introduce the option but not change the behavior, so that we can take a more comprehensive look soon. That's also the safer option anyway in terms of backwards compatibility.

**Review by ElenaKhaustova — APPROVED** [review]
Approving the PR not to block it, since the implementation looks good to me.

Agree to decide on making the `raise_errors=True` later on.

**Review by noklam — APPROVED** [review]
Thanks, a bit late to the discussion. I agree we should not change the behavior in a micro release.

In principle I like a default=True, but with concern about discoverability and the ergonomics of this. I imagine this is like a switch that you may need to turn on & off from time to time, going into `pipeline_registry.py` to do so feel inconsistent with other CLI options etc.

**Pull request merged**
