### PR TITLE
new feature: filename_prefix

### PR DESCRIPTION
**Pull request by drdebian**
- new parameter: filename_prefix
- allows filtering of incremental datasets residing in the same directory
- default checkpoint filename will also be prefixed if set
- should be back- and forwards compatible

## Description
https://github.com/kedro-org/kedro/discussions/1205
This patch enables the Partitioned- and IncrementalDataSets to filter
files by specifying a prefix. Only filesnames that start with this prefix
will be processed. In case of the IncrementalDataSet, the default
checkpoint filename will also be prefixed with the filename_prefix, to
allow for multiple such IncrementalDataSets to work from the same
directory.

### CODE REVIEW

**Comment by datajoely** [comment]
Hi @drdebian thank you so much for this - neat solution! Keen to get this merged, but there are a couple of steps that we need you need to follow as [per this guide](https://kedro.readthedocs.io/en/stable/14_contribution/02_developer_contributor_guidelines.html). The most important being including a couple of unit tests that demonstrate this functionality works as expected 😄  .

**Comment by drdebian** [comment]
> Hi @drdebian thank you so much for this - neat solution! Keen to get this merged, but there are a couple of steps that we need you need to follow as [per this guide](https://kedro.readthedocs.io/en/stable/14_contribution/02_developer_contributor_guidelines.html). The most important being including a couple of unit tests that demonstrate this functionality works as expected 😄 .

OK, I might need some help here. I'm on Windows (don't judge me) and it's not obvious to me how to produce a suitable test environment. I have no Circleci to begin with, maybe somebody could provide some pointers to get me started?

**Comment by datajoely** [comment]
Hi @drdebian - it's a pleasure to coach you through the process. 

Windows is absolutely fine this part of the docs details how to [get started](https://kedro.readthedocs.io/en/stable/14_contribution/02_developer_contributor_guidelines.html#before-you-start-development-set-up). You'll want to get to a point where you can run `make test` and then work through the issues.

**Comment by drdebian** [comment]
> Hi @drdebian - it's a pleasure to coach you through the process.
> 
> Windows is absolutely fine this part of the docs details how to [get started](https://kedro.readthedocs.io/en/stable/14_contribution/02_developer_contributor_guidelines.html#before-you-start-development-set-up). You'll want to get to a point where you can run `make test` and then work through the issues.

I'm sorry, the instructions don't explain to me how to bootrap a Windows development environment. How do I get make? How do I install Circleci?

**Comment by datajoely** [comment]
Hi @drdebian  what that means is that you can copy the windows commands we run in the CI step, you don't need to run CircleCI yourself:

https://github.com/kedro-org/kedro/blob/682fb793234ddabe5da55f45530329107c3e9048/.circleci/config.yml#L72

**Comment by MerelTheisenQB** [comment]
Hi @drdebian are you planning on completing this PR? Let us know if you need any help 🙂

**Comment by drdebian** [comment]
> Hi @drdebian are you planning on completing this PR? Let us know if you need any help 🙂

Thanks for the reminder. Right now I'm unable to complete the PR requirements due to personal time constraints.

**Pull request closed without merging**
