### PR TITLE
update docs to reflect change to /conf file structure

### PR DESCRIPTION
**Pull request by DimedS**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description
This PR updates the documentation to mirror the modifications made to the /conf file structure, as discussed in the following issues:

[#2752](https://github.com/kedro-org/kedro/issues/2752)
[#2753](https://github.com/kedro-org/kedro/issues/2753)
[#2844](https://github.com/kedro-org/kedro/issues/2844)

## Development notes
New /conf folder structure:
```
├── conf
    └── base
	├── catalog_{pipeline-name}.yml          #blank files
	└── parameters_{pipeline-name}.yml       #blank files
        ├── catalog.yml          #blank files   
	└── parameters.yml       #blank files
```

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by ankatiyar — COMMENTED** [review]
There is also a mention of the old `conf/` structure here -> https://docs.kedro.org/en/stable/nodes_and_pipelines/modular_pipelines.html#what-does-kedro-pipeline-create-do

**Comment by DimedS** [comment]
> There is also a mention of the old `conf/` structure here -> https://docs.kedro.org/en/stable/nodes_and_pipelines/modular_pipelines.html#what-does-kedro-pipeline-create-do

Ankita, thanks for pointing that out! Fixed

**Review by ankatiyar — APPROVED** [review]
Looks good to me! 😄

**Review by merelcht — APPROVED** [review]
LGTM! 👍

**Pull request merged**
