### PR TITLE
Bump `blacken-docs` hook version to fix regression

### LINKED ISSUE #1565: blacken-docs missing python failure
## Description
`blacken-docs` refers to cached pre-commit environment that does't exists

## Context
I wanted to create pull request with feature for further discussion, but failing at pre-commit check

## Steps to Reproduce
1. created environment: `conda create -n kedro python=3.10 -y`
2. installed requirements: `make install-test-requirements`
3. installed pre-commit hooks: `make install-pre-commit`
4. executed pre-commit hook: `make lint`

## Expected Result
Successful pass or `blacken-docs` internal exception

## Actual Result

```
blacken-docs.............................................................Failed
- hook id: blacken-docs
- exit code: 1

Executable `/home/atmosphere/.cache/pre-commit/repoiq31kknf/py_env-python3/bin/python` not found
```

```zsh
(kedro) ➜  kedro git:(parametrized-session-id) ✗ blacken-docs --skip-errors
Traceback (most recent call last):
  File "/home/atmosphere/miniconda3/envs/kedro/bin/blacken-docs", line 8, in <module>
    sys.exit(main())
  File "/home/atmosphere/miniconda3/envs/kedro/lib/python3.10/site-packages/blacken_docs.py", line 203, in main
    black_mode = black.FileMode(
  File "<string>", line 3, in __init__
TypeError: set object expected; got list
```
## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): under `main` branch by 23.05.2022
* Python version used (`python -V`): `Python 3.10.4`
* Operating system and version: `Ubuntu 20.04.3 LTS`

### PR DESCRIPTION
**Pull request by deepyaman**
Signed-off-by: Deepyaman Datta <deepyaman.datta@utexas.edu>

## Description

Closes #1565 

## Development notes

I somehow got into the business of standardizing `<project-name>` and `<python_package>`, since I missed the `--skip-errors` flag in the `blacken-docs` entrypoint (I forgot that there were two things that needed to be blackened that were actually failing the build).

On that note:

* It's a bit inconsistent to have `<project-name>` and `<python_package>` (dash and underscore, respectively), but I guess that's fair enough, since the actual package name really can't have a dash.
* You have a couple instances in https://github.com/kedro-org/kedro/blob/0.18.1/kedro/framework/session/session.py#L76-L87 with inexplicably roundabout terms for `<python_package>`, but I left them as is.
* A number of files use `<project-root>` or `<project_root>` instead of `<project-name>` and, while I think this could be standardized, there are instances like `<path-to-your-project-root>` in https://github.com/kedro-org/kedro/blob/0.18.1/docs/source/development/commands_reference.md that don't make sense as `<path-to-your-project-name>`. Maybe something to update in the lexicon?

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/1602"></a>

### CODE REVIEW

**Comment by deepyaman** [comment]
I somehow got into the business of standardizing `<project-name>` and `<python_package>`, since I missed the `--skip-errors` flag in the `blacken-docs` entrypoint (I forgot that there were two things that needed to be blackened that were actually failing the build).

On that note:

* It's a bit inconsistent to have `<project-name>` and `<python_package>` (dash and underscore, respectively), but I guess that's fair enough, since the actual package name really can't have a dash.
* You have a couple instances in https://github.com/kedro-org/kedro/blob/0.18.1/kedro/framework/session/session.py#L76-L87 with inexplicably roundabout terms for `<python_package>`, but I left them as is.
* A number of files use `<project-root>` or `<project_root>` instead of `<project-name>` and, while I think this could be standardized, there are instances like `<path-to-your-project-root>` in https://github.com/kedro-org/kedro/blob/0.18.1/docs/source/development/commands_reference.md that don't make sense as `<path-to-your-project-name>`. Maybe something to update in the lexicon?

**Review by AntonyMilneQB — APPROVED** [review]
Thank you very much for this 🙇

**Review by MerelTheisenQB — APPROVED** [review]
Thanks @deepyaman 🤩

**Review by noklam — APPROVED** [review]
thank you!

**Pull request merged**
