### PR TITLE
[AUTO-MERGE] Merge main into develop via merge-main-to-develop

### PR DESCRIPTION
**Pull request by idanov**
A new change in main cannot be merged into develop as part of the regular sync job, hence this PR. Please resolve the conflicts manually, and make sure to obtain 2 approvals once the builds pass.

### IMPORTANT NOTICE

Please let CircleCI merge this PR automatically, with merge commit enabled.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Will have a look at the `conf.py` conflicts later

**Review by merelcht — APPROVED** [review]

**Comment by astrojuanlu** [comment]
The conflict was not with `setup.py`, but with `docs/source/kedro.extras.logging.color_logger.ColorHandler.rst`, which was removed in 3fcf0fac51c7cc9e8be2654b403aefa0a475d28a.

**Comment by astrojuanlu** [comment]
```
Too long with no output (exceeded 10m0s): context deadline exceeded
```

🤔 Any clue at what's happening here?

**Comment by merelcht** [comment]
> ```
> Too long with no output (exceeded 10m0s): context deadline exceeded
> ```
> 
> 🤔 Any clue at what's happening here?

I've seen this happen before. Sometimes it seems to be CCI capacity.. I usually just rerun.

**Comment by astrojuanlu** [comment]
Okay yeah it was just flakiness. Now everything is green, guess this will merge itself.

**Pull request merged**
