### PR TITLE
Remove recommendations for databricks-connect

### PR DESCRIPTION
**Pull request by AhdraMeraliQB**
Signed-off-by: Ahdra Merali ahdra.merali@quantumblack.com

## Description
As Databricks is dropping support for databricks-connect, this change removes mentions and recommendations of it from Kedro documentation.

## Development notes
Removed sections on databricks-connect. 
Reworked surrounding sections to adjust to new context.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/1376"></a>

### CODE REVIEW

**Review by MerelTheisenQB — APPROVED** [review]
Great, thanks @AhdraMeraliQB ⭐ ⭐ 

Just a note on the [DCO check](https://kedro.readthedocs.io/en/stable/14_contribution/02_developer_contributor_guidelines.html?developer-certificate-of-origin) that's failing: now Kedro is part of the Linux Foundation every contributor is required to sign off their commits.
You can do this by following the steps here: https://github.com/kedro-org/kedro/pull/1376/checks?check_run_id=5722979682


To avoid having to do this every time you make a PR, you might want to do the following:
"you might like to set up an [alias](https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases) for git commit -s. Alternatively, run make sign-off to setup a [commit-msg Git hook](https://git-scm.com/docs/githooks#_commit_msg) that automatically signs off all commits (including merge commits) you make while working on the Kedro repository"

**Review by SajidAlamQB — APPROVED** [review]
Awesome!

**Comment by lorenabalan** [comment]
Not sure what happened here but it was fine to keep it as a PR against `develop`.

**Comment by AhdraMeraliQB** [comment]
Hi @lorenabalan, the commits did get a bit messy so I'll attempt to clarify - 

The base branch was originally main instead of develop, when I caught that I updated that to develop and merged that branch in. 

After merging, I was making the changes suggested by @MerelTheisenQB for the DCO check, but was having problems rebasing all the commits from develop, so we agreed to revert that commit and reset the base branch to main seeing as editing documentation isn't a breaking change. (ad973e4)

From then I was able to rebase and recommit with my sign-off to pass the DCO checks. (ebb92f9)

Hope this helps clarify the commit logs 😅 . The changes will be merged in once the CI fixes are pushed to main.

**Pull request merged**
