### PR TITLE
Draft PR for issue 1946 - Snowpark dataset

### PR DESCRIPTION
**Pull request by heber-urdaneta**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description

Addresing comments from previous draft PR

## Development notes

Draft implementation of SnowParkDataSet kedro/extras/datasets/snowflake/snowpark_dataset.py

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/2032"></a>

### CODE REVIEW

**Comment by datajoely** [comment]
Also as the PR description at the top says, we'll actually have to move all of this to the new [kedro-dataset](https://github.com/kedro-org/kedro-plugins/tree/main/kedro-datasets) standalone package.

**Review by datajoely — CHANGES_REQUESTED** [review]
I think in general we shouldn't be doing Pandas stuff in here, it should be a Snowpark dataset first and foremost the same was as we do with Spark - the user can transcode to Pandas later if they need to.

**Comment by datajoely** [comment]
@sfc-gh-mgorkow delighted to see you here! Keen to make some noise about this once it launches :)

**Comment by heber-urdaneta** [comment]
Development of snowpark integration moved to this PR: https://github.com/kedro-org/kedro-plugins/pull/78

**Pull request closed without merging**
