### PR TITLE
Minor dataset factories and config docs update

### PR DESCRIPTION
**Pull request by ankatiyar**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description

* Was just going through the `develop` docs and came across some missing quotes on dataset factory names in the docs. 
* An example in the configuration parameters is not relevant anymore since we moved the syntax for `--params` to use `=` instead of `:`
* `make install-pre-commit` installs all the test requirements too - I've removed it but can revert if this is intentional. The install test requirements step on GHA inadvertently calls `pip install .[test]` twice because of this.
## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by merelcht — APPROVED** [review]
LGTM! 👍 I think the installing of test reqs for `install-pre-commit` was intentional, but IMO it's better to have it separate.

**Comment by astrojuanlu** [comment]
RTD failure is legitimate 

```
sphinx.errors.SphinxWarning: /home/docs/checkouts/readthedocs.org/user_builds/kedro/checkouts/3337/docs/source/kedro_project_setup/starters.md:142:broken link: https://github.com/kedro-org/kedro-starters/tree/main/pandas-iris/%7B%7B%20cookiecutter.repo_name%20%7D%7D (404 Client Error: Not Found for url: https://github.com/kedro-org/kedro-starters/tree/main/pandas-iris/%7B%7B%20cookiecutter.repo_name%20%7D%7D)
```

**Review by astrojuanlu — APPROVED** [review]
Other than my comment, LGTM!

**Comment by ankatiyar** [comment]
@astrojuanlu Fixed it in #3338 and I think Jo is already cleaning the starters pages in a separate PR so I didn't touch those

**Pull request merged**
