### PR TITLE
Remove `setup.py`

### PR DESCRIPTION
**Pull request by merelcht**
## Description
Remove `setup.py` and move remainder of content to `pyproject.toml`

Closes part of https://github.com/kedro-org/kedro/issues/1498

## Development notes
I ended up just removing the little bit of code iterating over `template_files`. This was added waaaaay back in Kedro version `0.14.0` and has never been changed. I couldn't really figure out what it was doing.

I ran `python -m build` on the `main` branch and on this branch and compared the resulting tar files. The content is exactly the same. Unless I'm missing something I think that's sufficient proof that things are still working as expected even without the `template_files` stuff. 

Also updated the `pip install .` command in the e2e setup to `pip install -e .`.

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by astrojuanlu — APPROVED** [review]
YES! I confirm both the wheels and the sdists are identical 👍🏽

**Comment by merelcht** [comment]
> There seems to be a difference when you install the package with `pip install .`, which is making 2 of the e2e tests fail. I'll investigate!

Actually, there seems to be a difference when you install the package with `pip install .`, which is making 2 of the e2e tests fail. I'll investigate!

**Comment by merelcht** [comment]
> Actually, there seems to be a difference when you install the package with `pip install .`, which is making 2 of the e2e tests fail. I'll investigate!

Changing the command to `pip install -e .` seems to have fixed it. This is mentioned as the command to use for installing the local directory.

**Review by ankatiyar — APPROVED** [review]
🪦 `setup.py`

**Pull request merged**
