### PR TITLE
Fixed error message whitespace

### PR DESCRIPTION
**Pull request by puneet29**
Added whitespace in one of the error messages where it was missing for better readability.

## Description
White space was missing in one of the error messages.

## Development notes
Just added the whitespace to the error string. This is a minor change in just the string, don't think it needs testing.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by datajoely — APPROVED** [review]

**Comment by datajoely** [comment]
Good spot!

**Comment by puneet29** [comment]
Hey @datajoely , maybe I will sound like a noob right now.  But why are the builds failing? I just changes one line of code and I don't suppose there are any test cases around that error either. Is the main build stable? Would love to be educated 😅

**Comment by datajoely** [comment]
Hi @puneet29 it's not you it's us we're currently fixing it :)

**Comment by lorenabalan** [comment]
Hi @puneet29, thanks for the first contribution! Ignore the CI failures for now. Could you just double check tests are passing? i.e. run `make test` or `pytest tests`

One thing we do need to ask all our users to do though is to sign-off their commits - this is what the DCO plugin checks. Can you please try the following commands

```
git commit --amend --no-edit -s
git push -f
```

This will amend the last edit with a sign-off, and `push -f` will overwrite the one already pushed to the remote. Then you can merge the `main` branch into your branch to update it. 
If you wish to set up your env to be more comfortable for future Kedro contributions, just run `make sign-off` to make sure all your commits are automatically signed off.

**Review by lorenabalan — APPROVED** [review]

**Pull request merged**
