### PR TITLE
Bump `kedro-datasets` to 2.0.0

### PR DESCRIPTION
**Pull request by merelcht**
## Description
Bump `kedro-datasets` to the latest `2.0.0` release.

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Docs need to be built on Python 3.9 now (hence the installation issues)

**Comment by astrojuanlu** [comment]
https://github.com/kedro-org/kedro/blob/1cd7d610eb30639d8cf9758902c5a4737f9926be/pyproject.toml#L82

Guessing that we can remove `s3fs` from our test requirements?

**Comment by merelcht** [comment]
> https://github.com/kedro-org/kedro/blob/1cd7d610eb30639d8cf9758902c5a4737f9926be/pyproject.toml#L82
> 
> Guessing that we can remove `s3fs` from our test requirements?

No this is needed for testing cloud interactions via fsspec. 

It looks like the docs are still the issue...

**Comment by astrojuanlu** [comment]
```
sphinx.errors.SphinxWarning: /home/docs/checkouts/readthedocs.org/user_builds/kedro/checkouts/3405/docs/source/data/advanced_data_catalog_usage.md:14:unknown document: 'kedro-datasets:kedro_datasets'
```

**Comment by astrojuanlu** [comment]
Unsure why the builds are taking so long, but I confirm locally that the docs are building.

**Comment by astrojuanlu** [comment]
It's because of conflicting dependencies. However, _maybe_ we don't need kedro-datasets anymore to build the docs...!

**Review by astrojuanlu — APPROVED** [review]
✔️

**Comment by astrojuanlu** [comment]
RTD build times cut in half ✌🏽

**Review by ankatiyar — APPROVED** [review]

**Pull request merged**
