### PR TITLE
Add method to remove runtime patterns after run

### PR DESCRIPTION
**Pull request by ElenaKhaustova**
## Description
After the pattern resolution logic refactoring we process all the patterns (`dataset`, `default`, `runtime`) together.

As a result of `run()` we return:

>       datasets that aren't in the catalog and don't match a pattern in the catalog and include MemoryDataset
https://github.com/kedro-org/kedro/blob/ba981350ad57dbcaabf5fd758a9a3d4399a91f20/kedro/runner/runner.py#L108

Before the `run()` we add a runtime pattern to the catalog, so we could process all intermediate outputs as `MemoryDataset`.

So currently when we do two consecutive runs https://github.com/kedro-org/kedro/issues/4235 runtime pattern `{default}` added after the first run affects the next runs, so that all datasets match it and we do not return anything as a result of `run()` cause we think these datasets are in the catalog.

## Development notes
We think that the resolution logic is correct and all patterns should be processed together as we do now. To avoid [this behaviour ](https://github.com/kedro-org/kedro/issues/4235) we added method to remove runtime patters after the run, so they only live within the run and do not affect other runs.

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by noklam** [comment]
>   datasets that aren't in the catalog and don't match a pattern in the catalog and include MemoryDataset

If a dataset is defined in catalog or as a pattern, the catalog would not return as, with the exception of **MemoryDataset**. In this case it should be still return because the runtime pattern add a memory dataset. Can you clarify why changing the pattern resolution somehow breaks this?


https://github.com/kedro-org/kedro/pull/3475

**Comment by ElenaKhaustova** [comment]
> > datasets that aren't in the catalog and don't match a pattern in the catalog and include MemoryDataset
> 
> If a dataset is defined in catalog or as a pattern, the catalog would not return as, with the exception of **MemoryDataset**. In this case it should be still return because the runtime pattern add a memory dataset. Can you clarify why changing the pattern resolution somehow breaks this?
> 
> #3475

As I tried to explain above after we add `runtime` pattern - which matches all datasets it remains in the catalog when the second run, this part of the condition is not valid `don't match a pattern in the catalog`. Previously there was a different logic when resolution and `runtime` patterns were processed separately.

**Comment by noklam** [comment]
I get this in the second run it will be in the `registered_ds`. But the logic here is:
free_output =  output - register_ds (excluding if is a memory dataset)

So my expectation here is that, even if it's registered, it will still be return.

https://github.com/kedro-org/kedro/blob/ba981350ad57dbcaabf5fd758a9a3d4399a91f20/kedro/runner/runner.py#L110

Trace:
I run this twice in the test and add some printing statement in `runner.py`

```
pipeline.outputs()=set()
registered_ds=['params:model_options', 'model_input_table']
memory_datasets={'params:model_options', 'model_input_table'}
free_outputs=set()

pipeline.outputs()=set()
registered_ds=['X_test', 'params:model_options', 'X_train', 'y_test', 'y_train', 'model_input_table', 'regressor']
memory_datasets={'params:model_options', 'model_input_table'}
free_outputs=set()
```

**Comment by ElenaKhaustova** [comment]
> This is the result I get with other test, I think the problem is where we define Memory dataset, in 2nd run I expected, y_test, X_test, regressor in the memory_datasets

They are not in the catalog because we make

```
        catalog = catalog.shallow_copy(
            extra_dataset_patterns=self._extra_dataset_patterns
        )
```

before calling `_run()`, so we modify different object. But `runtime` pattern is stored in `CatalogConfigResolver`, so it remains the same between the runs.

In the new catalog, it will be as you expect.

**Comment by ElenaKhaustova** [comment]
Please note that `shallow_copy` will be removed from the new catalog, but the mechanism to remove runtime patterns after the run will be helpful anyway to not affect consequent runs.

**Review by ankatiyar — APPROVED** [review]
Given that we are removing `shallow_copy` stuff in the future, this solution makes sense to me! Thanks @ElenaKhaustova 👍🏾

**Comment by ElenaKhaustova** [comment]
Moved to draft now as want to double-check some cases that @noklam shared.

**Comment by noklam** [comment]
For reference I shared my edge cases here: https://github.com/noklam/kedro-runner-bug-investigation/commits/main/

**Review by noklam — APPROVED** [review]

**Review by merelcht — APPROVED** [review]
LGTM!

**Review by ankatiyar — APPROVED** [review]
Thanks @ElenaKhaustova 👍🏾

**Pull request merged**
