### PR TITLE
Update faq.md fixing label formatting

### PR DESCRIPTION
**Pull request by qheuristics**
Remove unneeded :code: word

> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by stichbury — APPROVED** [review]
LGTM, thanks! 🏆

**Comment by stichbury** [comment]
@qheuristics Please could you check the DCO failure by signing your commit message? https://github.com/kedro-org/kedro/pull/3005/checks?check_run_id=16469193901

**Review by astrojuanlu — APPROVED** [review]
Good catch @qheuristics! Will merge when the DCO check passes

**Comment by stichbury** [comment]
Just a swift note to page @qheuristics -- we would love to merge your PR but we need the DCO to pass https://github.com/kedro-org/kedro/pull/3005/checks?check_run_id=16469193901 (please could you take a look at the guidance for this or use `git commit --amend --no-edit --signoff` if it's just the single commit that needs it.

**Comment by astrojuanlu** [comment]
Thanks @qheuristics!

**Pull request merged**
