### PR TITLE
Ensure the tools example selection uses the same starter version as kedro

### PR DESCRIPTION
**Pull request by SajidAlamQB**
## Description

A user who was trying to follow our [First Steps](https://docs.kedro.org/en/stable/get_started/index.html) guide ran into a an issue whilst executing `kedro run` as specified in the [Run the new project](https://docs.kedro.org/en/stable/get_started/new_project.html#run-the-new-project) step. 

With the following errors:

```
TypeError: ProjectMetadata.__new__() got an unexpected keyword argument 'example_pipeline'
RuntimeError: Found unexpected keys in 'pyproject.toml'. Make sure it only contains the following keys: ['package_name', 'project_name', 'kedro_init_version', 'source_dir', 'tools'].
```

In our `_make_cookiecutter_args_and_fetch_template` function we fetch the main branch of `kedro-starters`, this has the potential to make our starters go out of sync with the current released version of `Kedro` as the example above has shown. Instead, as we do with `--starters` flag, we should pass the `checkout` argument with the `kedro` version to cookiecutter to make sure cookiecutter uses the same version of `kedro_starters` as `kedro`. This will ensure that when using the new tools example selection the starters are always aligned to the same version as `kedro`.

## Development notes

I've added `cookiecutter_args["checkout"] = version` to each starter we pull with tools.

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by AhdraMeraliQB — COMMENTED** [review]
Why isn't this handled by line 299?

**Comment by SajidAlamQB** [comment]
> Why isn't this handled by line 299?

Thats dealing with `--starters` flag which has no effect on the starters that are being pulled by `--tools` from what I understand.

**Review by DimedS — APPROVED** [review]
Thank you @SajidAlamQB , very good catch! Maybe we should think about some test on that topic

**Comment by merelcht** [comment]
In https://github.com/kedro-org/kedro/blob/031f87f3b48d8ec2f089cbb3bf1c23784ee6e55e/kedro/framework/cli/starters.py#L727-L728 we set the `checkout` to `checkout` if a value is provided. But now that would be overwritten by version every time. Does that have unexpected consequences?

**Comment by SajidAlamQB** [comment]
> we set the `checkout` to `checkout` if a value is provided. But now that would be overwritten by version every time. Does that have unexpected consequences?

There shouldn't be any unexpected consequences as `--tools` and `--checkout` shouldn't be used together its only used with `--starter` and that remains unaffected.

**Comment by merelcht** [comment]
> > we set the `checkout` to `checkout` if a value is provided. But now that would be overwritten by version every time. Does that have unexpected consequences?
> 
> There shouldn't be any unexpected consequences as `--tools` and `--checkout` shouldn't be used together its only used with `--starter` and that remains unaffected.

Oh yes of course that's the indirect rule enforced here: https://github.com/kedro-org/kedro/blob/031f87f3b48d8ec2f089cbb3bf1c23784ee6e55e/kedro/framework/cli/starters.py#L136

**Review by merelcht — APPROVED** [review]
LGTM! 👍

**Pull request merged**
