### PR TITLE
Docs/update viz image iris starter

### LINKED ISSUE #3108: Incorrect Pipeline Visualization in Iris Kedro Tutorial
Hi, I've noticed in the Iris starter tutorial a screenshot, but the screenshot apparently belongs to the spaceflights starter. The Iris screenshot is this one.

image

Appologies if I missunderstood the project.

### PR DESCRIPTION
**Pull request by laizaparizotto**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description
This PR was created in order to Resolve #3108. There is a wrong image for the visualisation of `kedro viz` for `iris` starter

## Development notes
- Started a new project with  `kedro new --starter=pandas-iris`
- ran `kedro viz` and got the correct visualization.
- Added the `.png` image to the folder `docs/source/meta/images/pipeline_visualisation_iris_starter.png`.
- Changed the reference link at `docs/source/get_started/new_project.md`

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by stichbury — APPROVED** [review]
Nice spot! Thanks for adding this graphic 🌟

**Comment by stichbury** [comment]
Docs build is now working. The page is here: https://kedro--3141.org.readthedocs.build/en/3141/get_started/new_project.html#summary

**Comment by stichbury** [comment]
This is ready to go now, just one extra review needed pls!

**Review by ankatiyar — APPROVED** [review]
Thanks @laizaparizotto!

**Comment by stichbury** [comment]
Thanks @laizaparizotto this was much appreciated. Nice contribution and great catch! 🏆

**Pull request merged**
