### PR TITLE
Added ac_context parameter to config.common

### PR DESCRIPTION
**Pull request by MigQ2**
## Description
Added anyconfig's `ac_context` parameter to `kedro.config.commons` module functions for more flexible `ConfigLoader` customizations.

I think this is helpful because I wanted to customize my `ConfigLoader` to use a custom `ac_context` to resolve some macros in my configuration files, but I couldn't do it just by extending the `ConfigLoader` class, as all teh logic was in `kedro.config.commons`. 

This PR would allow my team and other teams in the future to more easily customize and add functionality to `ConfigLoader`

## Development notes
Tested with `make test`

## Checklist

- [X] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [X] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [X] Updated the documentation to reflect the code changes
- [X] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [] (Does not apply) Added tests to cover my changes 

CC @ak4wa1

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/2109"></a>

### CODE REVIEW

**Comment by merelcht** [comment]
Hi @MigQ2 thanks for opening this PR. 

We're working on big changes to configuration, which includes replacing `anyconf` with `OmegaConf` (see this issue for more details https://github.com/kedro-org/kedro/issues/1657). In Kedro `0.19.0` we'll also be getting rid of our legacy `ConfigLoader` class and the accompanying helper methods in `config/common.py`, because as you've noticed this setup doesn't allow you to create your own `ConfigLoader` implementation very easily. 

With that in mind, I'd prefer not to make any changes to `ConfigLoader` (or `TemplatedConfigLoader`) and would suggest you just use your customisation for your own use case. 

Let me know what you think and if you have any questions 🙂

**Comment by idanov** [comment]
@merelcht I think that this is a very small change, which will be gone with 0.19.0, but it might be potentially useful for a 0.18.5 release. In that context, it might be worth getting it in (since it won't affect much future versions).

**Review by merelcht — APPROVED** [review]
Ivan has a point that it would be useful to get this functionality in while our config loaders still make use of `anyconf` 🙂 

Thanks for the addition @MigQ2, LGTM 👍

**Review by idanov — APPROVED** [review]
LGTM! One note here is that this will be gone most likely in 0.19.0 in favour of the changes introduced by https://github.com/kedro-org/kedro/pull/2085

**Pull request merged**
