### PR TITLE
Add coverage report to help debugging

### PR DESCRIPTION
**Pull request by noklam**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description

We use `coverage` to check which part of the source code is covered. It is useful to answer this question sometimes.
> Which test run this lines?

To test this
1. Run some tests
2. `make show-coverage`
3. Open the `index.html` in a browser or Right-click Open with live server (On GitPod)

You should see a index page. If you click into a specific module, it will shows you which tests execute that line of code.
image

image

## Development notes

- Add new flag `--cov-context`
- Add a helper function `make show-coverage

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by astrojuanlu — COMMENTED** [review]
I tried this locally and didn't work:

```
================ 35 failed, 2097 passed, 3 skipped, 19 xfailed, 2 xpassed, 3 warnings in 830.79s (0:13:50) =================
make: *** [test-no-spark] Error 1
  ~/Projects/QuantumBlack Labs/kedro  noklam/coverage-report *3 ?3 ···································  13m 51s 11:20:55
❯ make show-coverage                                                                                          (kedro38-dev) 
coverage html --show-contexts || true
/Users/juan_cano/.micromamba/envs/kedro38-dev/lib/python3.8/site-packages/coverage/html.py:116: CoverageWarning: No contexts were measured
  self.coverage._warn("No contexts were measured")
Wrote HTML report to htmlcov/index.html
Coverage failure: total of 0 is less than fail-under=100
open htmlcov/index.html
```

(the report shows that all lines were missing, despite some tests being successful)

**Comment by noklam** [comment]
@astrojuanlu noted that you have 0 coverage, it looks like a setup problem. Try doing pip install -e. Again ?

**Comment by astrojuanlu** [comment]
Repeated `pip install -e ".[test]" && make test-no-spark`, then `make show-coverage`, still 0

**Comment by ankatiyar** [comment]
It works for me finally, all the tests have to pass first. `make test-no-spark` etc have `--no-cov` flag, that is maybe why it's not working @astrojuanlu. If you run `pytest <test_path>` and then do `make show-coverage` it works!

**Comment by ankatiyar** [comment]
This is incredibly helpful @noklam Thanks! :D

**Comment by noklam** [comment]
>It works for me finally, all the tests have to pass first. make test-no-spark etc have --no-cov flag, that is maybe why it's not working @astrojuanlu. If you run pytest <test_path> and then do make show-coverage it works!
> @ankatiyar 

I was thinking how could I make this better, then I realise in `develop` there will be no `test-no-spark`, the only command left is just `test`. You are right that either `pytest` (that's how I usually run tests for a particular module, I rarely run for all as it takes too long), or `make test` should work.

**Review by merelcht — APPROVED** [review]
This is great! Thanks @noklam 😄

**Pull request merged**
