### PR TITLE
[DRAFT - DON'T MERGE] - SoftFailRunner

### PR DESCRIPTION
**Pull request by noklam**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by noklam** [comment]
do not merge this PR, will leave this until we finalised. We could leave here or refer it to the upcoming blog post instead.

**Comment by stichbury** [comment]
@noklam I'm thinking of publishing the blog post about this in 2 weeks time (21st June) and wondered if there's likelihood this will be merged so I can point to it here on Kedro?

**Comment by noklam** [comment]
@stichbury I don't think it will be merged soon, if we want to merge this it will still requires some fix to make it consistent as other runners and create some tests for it.

I'll put this in backlog grooming so the team can decide the priority of this.

**Comment by astrojuanlu** [comment]
It's annoying but keeping the PR open prevents us from accidentally deleting the branch. I don't think merging this is a priority, but maybe we could copy paste the code somewhere safe (its own package maybe) and then close this PR for now.

**Comment by noklam** [comment]
It's just one file. I keep it in a [gist](https://gist.github.com/noklam/b56314d75fc495ab0dc922b3c2e80cef) for now.

**Pull request closed without merging**
