### PR TITLE
Draft Pull Request : Add incremental run method

### PR DESCRIPTION
**Pull request by pedro-sarpen**
## Description
Add `AbstractRunner.run_incremental` method. 
Allows to automatic skip re-running already existing intermediate node outputs.

## Development notes
This is a RFC PR.
The feature seems quite useful to avoid re-running expensive nodes. Yet there was no similar feature in the API.
Explicity specifying the nodes is tedious and may be prone to errors, requiring multiples runs to figure which nodes one needs to run.

Any comments on if it is the best place to add the feature or if there is a better solution are welcome.

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/2005"></a>

### CODE REVIEW

**Comment by noklam** [comment]
Thank you for your PR, this looks quite similar to this.

What is not supported by this already?

https://github.com/kedro-org/kedro/blob/f52249b262b8716d40cbfac80de0198980390bb2/kedro/runner/runner.py#L94-L121

**Comment by pedro-sarpen** [comment]
> Thank you for your PR, this looks quite similar to this.
> 
> What is not supported by this already?
> 
> https://github.com/kedro-org/kedro/blob/f52249b262b8716d40cbfac80de0198980390bb2/kedro/runner/runner.py#L94-L121

`run_only_missing` looks only for pipeline inputs / outputs, intermediate nodes are not accounted.
For example, if a pipeline output is missing it still run intermediate nodes even if a CachedDataSet for them already exists.

**Comment by merelcht** [comment]
Hi @pedro-sarpen, thanks for raising this PR! This is quite a big feature, so the maintainer team would like to discuss it in a Technical Design meeting to decide on best implementation. It might take a while for us to get to it, but know that we haven't forgotten your PR 🙂

**Comment by jmholzer** [comment]
Tech design 01/02/23:

- We decided to open a new issue to gather thoughts and discuss this in more depth in a future tech design session.

**Comment by jmholzer** [comment]
Hey @pedro-sarpen thanks for opening this PR 🙂.

As an update for you, the next steps for this feature are:

1. A new parent ticket which states and frames the problem (nodes with persisted outputs being re-run unnecessarily).
2. A technical design session (or investigation ticket) to define the possible solutions.
3. An implementation ticket.

Generally the way we consider new features in Kedro is by opening an issue with a high-level discussion of the problem before we go to problem-solving and implementation (starting at step 1 above).

This is a great suggestion and it's good to have this issue on our radar, though this PR goes straight to step 3. We may find a better solution to the underlying problem by starting at step 1.

I will leave this PR open, as it may be we decide this is the right way to go. In the mean time, I will open a ticket to kickstart the process above 🙂.

**Pull request closed without merging**
