### PR TITLE
[AUTO-MERGE] Merge main into develop via merge-main-to-develop

### PR DESCRIPTION
**Pull request by idanov**
A new change in main cannot be merged into develop as part of the regular sync job, hence this PR. Please resolve the conflicts manually, and make sure to obtain 2 approvals once the builds pass.

### IMPORTANT NOTICE

Please let CircleCI merge this PR automatically, with merge commit enabled.

### CODE REVIEW

**Review by noklam — APPROVED** [review]

**Comment by noklam** [comment]
I don't think it's too important to fix the datasets issue here, since `dev` is for 0.19.0 and we will remove datasets from `kedro`. It takes too much effort to maintain 3 different "branches". We have
- `kedro.extras` (main)
- `kedro.extras` (dev, for 0.19, shouldn't need it anymore)
- `kedro-datasets`

**Review by astrojuanlu — CHANGES_REQUESTED** [review]
Some linting issues still remaining

**Comment by noklam** [comment]
@astrojuanlu I have another PR fixing `dev` so I can address the docs issue there

**Review by noklam — APPROVED** [review]
Don't merge this with squash, background CI job will pick this up.

**Pull request merged**
