### PR TITLE
Add Kedro Coffee Chat section

### PR DESCRIPTION
**Pull request by ElenaKhaustova**
## Description
Added a section about coffee chat to the docs as a replacement of the old private page: https://github.com/McK-Internal/kedro-coffee-chat

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by merelcht — APPROVED** [review]
👍

**Comment by noklam** [comment]
Maybe Readme is too crowd for this? Would it be better to this section in Wiki and only keep the mention in Readme?

In docs we can add a community section too though we haven't added the slack channel in docs yet.

**Comment by ankatiyar** [comment]
Agree with @noklam, maybe just the first bit and a link to the announcement channel. The rules and the structure could go in a wiki with upcoming topics and dates too?

**Comment by ElenaKhaustova** [comment]
Added a wiki page as suggested above and updated readme with a reference to it: https://github.com/kedro-org/kedro/wiki/Kedro-Coffee-Chat

**Review by ankatiyar — APPROVED** [review]
👏🏾

**Review by merelcht — APPROVED** [review]

**Review by astrojuanlu — APPROVED** [review]
LGTM! ☕

**Pull request merged**
