### PR TITLE
[Ready] Changes to improve existing content about notebook development & kedro

### PR DESCRIPTION
**Pull request by stichbury**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description
[Built docs are here](https://kedro--3127.org.readthedocs.build/en/3127/notebooks_and_ipython/kedro_and_notebooks.html)

This answers #2845 by improving the content of the documentation page that describes how to combine a Kedro project with notebooks for data exploration. It also removes the `standalone-datacatalog` page which was ill-advised as it's not really about notebooks ([I've moved it temporarily into the README for the starter](https://github.com/kedro-org/kedro-starters/pull/156)).

This is part of a pair of PRs (#3128 is the other) to revise notebook docs. This one describes the "Add a notebook to Kedro projects" workflow, while #3128 describes the "Add Kedro to a notebook" workflow. They meet in the middle but I've separated them because I didn't want any one PR getting too complex. 

## Development notes
Changes to screenshots and copy. 
## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by stichbury** [comment]
I'm not sure why the RTD build is failing as I've built successfully locally

**Review by merelcht — APPROVED** [review]
Looks great! 👍 ⭐

**Review by SajidAlamQB — APPROVED** [review]
Thank you @stichbury! 🌟

**Review by astrojuanlu — APPROVED** [review]
Sorry for the delayed review, this somehow fell through the cracks.

I think this PR is an improvement over what we had before and it's ready to go in. However,  I also believe that the real game changer for this page will be de-emphasizing custom kernels, de-emphasizing `kedro jupyter`, and placing more emphasis in `%load_ext kedro.ipython`, as I suggested in this other issue https://github.com/kedro-org/kedro/issues/2777 

That can be done in a separate PR so LGTM 👍🏽

**Review by ankatiyar — APPROVED** [review]
Read through the built docs and it looks great!

**Pull request merged**
