### PR TITLE
Remove `kedro.extras.datasets` and `kedro.extras`

### LINKED ISSUE #2126: Remove `kedro.extras.datasets` from Kedro
### Description

- Remove `kedro.extras.datasets` (and `kedro.extras` too)
- Remove all related tests

PR should go to `dev`

### PR DESCRIPTION
**Pull request by noklam**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description

partial  #2126 

## Development notes

- Added `kedro_datasets` for testing requirements
- Update the imports to `kedro_datasets` in tests, doc change will be handled by #2287 
- Remove the 

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by noklam** [comment]
Alright I keep getting weird files push into the repo, I will just force push this and clone a new repo.

**Comment by noklam** [comment]
A separate PR to address the coverage/test problem. Noted I change `coverage` temporarily because we now missing some coverage as we removed the `kedro.extra.datasets`

**Review by merelcht — APPROVED** [review]
image

**Review by deepyaman — APPROVED** [review]
:shipit:

**Comment by deepyaman** [comment]
Maybe remove the line from https://github.com/kedro-org/kedro/blob/main/.github/PULL_REQUEST_TEMPLATE.md about datasets moving? Don't imagine people will try to add them here, if it doesn't exist.

**Comment by noklam** [comment]
@deepyaman will do in follow up datasets issues.

**Comment by noklam** [comment]
Removed the rst files and hopefully the docs build successfully.

**Comment by astrojuanlu** [comment]
Good night

**Pull request merged**
