### PR TITLE
Parametrized session_id

### LINKED ISSUE #1565: blacken-docs missing python failure
## Description
`blacken-docs` refers to cached pre-commit environment that does't exists

## Context
I wanted to create pull request with feature for further discussion, but failing at pre-commit check

## Steps to Reproduce
1. created environment: `conda create -n kedro python=3.10 -y`
2. installed requirements: `make install-test-requirements`
3. installed pre-commit hooks: `make install-pre-commit`
4. executed pre-commit hook: `make lint`

## Expected Result
Successful pass or `blacken-docs` internal exception

## Actual Result

```
blacken-docs.............................................................Failed
- hook id: blacken-docs
- exit code: 1

Executable `/home/atmosphere/.cache/pre-commit/repoiq31kknf/py_env-python3/bin/python` not found
```

```zsh
(kedro) ➜  kedro git:(parametrized-session-id) ✗ blacken-docs --skip-errors
Traceback (most recent call last):
  File "/home/atmosphere/miniconda3/envs/kedro/bin/blacken-docs", line 8, in <module>
    sys.exit(main())
  File "/home/atmosphere/miniconda3/envs/kedro/lib/python3.10/site-packages/blacken_docs.py", line 203, in main
    black_mode = black.FileMode(
  File "<string>", line 3, in __init__
TypeError: set object expected; got list
```
## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): under `main` branch by 23.05.2022
* Python version used (`python -V`): `Python 3.10.4`
* Operating system and version: `Ubuntu 20.04.3 LTS`

### PR DESCRIPTION
**Pull request by ARashitov**
### Use case

I have web application where I use kedro inside of endpoints. This web application has centralized logs, but I'm struggling with tracing which kedro session is executed for which endpoint since application is horizontally scaled.

### How I resolve this one

I add `session_id` argument to `KedroSession.create()` function and then i implemented kedro hooks for logging and linking with endpoints trace id

## Development notes

- [x] Updated `blacken-docs` revision in pre-commit (Resolves #1565)
- [x] Added `session_id` argument to `KedroSession.create()`
- [x] Added test case checking parametrized kedro session

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [x] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [x] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/1571"></a>

### CODE REVIEW

**Comment by datajoely** [comment]
Related to this issue raised by @noklam https://github.com/kedro-org/kedro/issues/1551

**Comment by noklam** [comment]
I think there are 2 points to discuss here:
1. Does `save_version = session_id` still valid? Or do we need something more? In the context of #1551, what user need is an ID for the entire DAG run instead of the individual session.
2. I didn't expect kedro pipeline will be used as an endpoint. Currently we have 1 session = 1 run, any addition run would required recreating the entire KedroSession which may be kind of slow. Do we need some kind of function like `KedroSession.reset()` that simply reset the flag & timestamp?

**Comment by MerelTheisenQB** [comment]
This is an interesting use case, and I think it's definitely worth discussing ways for users to control the `session_id` with the team. The `KedroSession` is still one of the more unstable components in Kedro, so I'd like to investigate more what potential use cases this would solve, before adding another argument to the user facing `create` method. One concern I have now is that we'd need to be careful about the format of `session_id` the user can provide. Currently, the session_id will be taken as the `save_version` as well and if this doesn't comply with the following rules, versioning will be broken:
```
a) be a case-insensitive string that conforms with operating system filename limitations, 
b) always return the latest version when sorted in lexicographical order.
```

Thanks for opening up this PR @AtmosOne, it might not be merged soon, but it's definitely food for thought.

**Comment by datajoely** [comment]
>  One concern I have now is that we'd need to be careful about the format of `session_id` the user can provide. Currently, the session_id will be taken as the `save_version` as well and if this doesn't comply with the following rules, versioning will be broken:
>
> ```
> a) be a case-insensitive string that conforms with operating system filename limitations, 
> b) always return the latest version when sorted in lexicographical order.
> ```
> 
> Thanks for opening up this PR @AtmosOne, it might not be merged soon, but it's definitely food for thought.


On these constraints, I was thinking we could allow the user to specify a `session_id` suffix which is appended to the end, this would meet requirement (b) and we could validate to ensure (a) is met.

**Comment by AtmosOne** [comment]
@MerelTheisenQB @datajoely Thank you! 
@MerelTheisenQB Where I could read more about requirements like the ones you sent & more about session versioning?

**Comment by noklam** [comment]
@AtmosOne There are no specific documents, you have to look into source code for this. This is more about how KedroSession trigger a run and how versioning works.

**Comment by MerelTheisenQB** [comment]
> @AtmosOne There are no specific documents, you have to look into source code for this. This is more about how KedroSession trigger a run and how versioning works.

@AtmosOne, Nok is right, we don't have any specific docs about this currently. The main reason for this is that we are still designing the `KedroSession` and the version we have right now will likely change in the future. We would advise users not to implement anything that heavily relies on what the `KedroSession` is now, unless of course you make your own version that can stand alone from Kedro. `KedroSession` is really more of a "back of house" component and as such not (yet) ready to be heavily used by users other than the framework developers.

**Comment by merelcht** [comment]
Closing this PR as it's very out of date with our `main` branch now. We'll take the suggestions and ideas here into account when redesigning how Kedro Session works. I'd suggest to anyone who wants to continue the conversation to create an issue or[ join our Slack](https://slack.kedro.org/) and chat there 🙂

**Pull request closed without merging**
