### PR TITLE
Add pip freeze stage to docs build CI

### PR DESCRIPTION
**Pull request by AntonyMilneQB**
## Description
Following the recent Sphinx CI saga, I've added a `pip freeze` stage to the process so that it's easier to troubleshoot in future.

I've slightly rejigged things so that `make build-docs` is a bit faster (no longer tries to re-install `test_requirements.txt`; removed redundant ipython thing).

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/1814"></a>

### CODE REVIEW

**Review by AhdraMeraliQB — APPROVED** [review]
Awesome! This was definitely much needed 😬

**Review by noklam — APPROVED** [review]
Thanks, it would be nice if `pip freeze` happens before the doc gets built but after the libraries are installed. If something breaks during the make-docs, we won't see which `sphinx-xxx` libraries are installed as this `pip freeze` won't be executed.

I agree it is cleaner to move the `pip install` to `Makefile` and remove the `test_requirements.txt`

```
	pip install -e ".[docs]"
        # pip freeze
	./docs/build-docs.sh "docs"
```

**Comment by noklam** [comment]
It would be nice if `pip freeze` happens before the doc gets built but after the libraries are installed. If something breaks during the make-docs, we won't see which `sphinx-xxx` libraries are installed.

```
	pip install -e ".[docs]"
        # pip freeze
	./docs/build-docs.sh "docs"
```

**Comment by AntonyMilneQB** [comment]
@noklam Ahdra had exactly the same thought when we were discussing this earlier. This is why there's `when: always` in the `pip freeze` step. This means that it will always be run, even if `make build-docs` crashes 🙂

**Review by noklam — APPROVED** [review]

**Comment by noklam** [comment]
@AntonyMilneQB Got it! Thanks for explaining.

**Pull request merged**
