### PR TITLE
Add gdrive to CLOUD_PROTOCOLS list

### PR DESCRIPTION
**Pull request by SajidAlamQB**
Signed-off-by: SajidAlamQB <90610031+SajidAlamQB@users.noreply.github.com>

## Description

related issue: https://github.com/kedro-org/kedro/issues/1632

Raised a [PR](https://github.com/fsspec/filesystem_spec/pull/988) on fsspec repo to introduce support for some of the missing cloud protocols. In the meantime, this PR will add the missing protocols for Kedro.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/1708"></a>

### CODE REVIEW

**Comment by datajoely** [comment]
Have we not discussed removing the need to add these manually?

**Comment by SajidAlamQB** [comment]
> Have we not discussed removing the need to add these manually?

Yes, you are right, we are trying to go back to using `infer_storage_options` from fsspec but holding out on a PR I opened on their end being merged.

**Comment by datajoely** [comment]
Ah nice! Adding this for visibility 
https://github.com/fsspec/filesystem_spec/pull/988

**Comment by SajidAlamQB** [comment]
Closing, PR on fsspec was merged.

**Review by AntonyMilneQB — APPROVED** [review]

**Comment by AntonyMilneQB** [comment]
Re-opened this since the fsspec fix got reverted: see https://github.com/fsspec/filesystem_spec/issues/1002.

**Review by MerelTheisenQB — APPROVED** [review]
👍

**Pull request merged**
