### PR TITLE
Fix Docstring example for PickleDataSet

### LINKED ISSUE #1976: pickle.PickleDataSet docstring examples are incorrect
## Description
Kind of a small issue but the "advanced" example in the [pickle.PickleDataSet API docs](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.pickle.PickleDataSet.html) is wrong.
`compression` is not a valid [`joblib.dump`](https://joblib.readthedocs.io/en/latest/generated/joblib.dump.html) parameter (it should simply be `compress`) and [`joblib.load`](https://joblib.readthedocs.io/en/latest/generated/joblib.load.html) does not require a `compression` kwarg at all since it can automagically discover the correct compression algorithm used.

## Context
Even if it's a trivial issue I stumbled upon it and I hope to fix it so that future users will not have to go the joblib docs to find the problem.

## Possible Alternatives
I'a m working on a trivial fix, I'm going to open a PR as soon as possible.

### PR DESCRIPTION
**Pull request by Kastakin**
## Description
Fixes #1976 

## Development notes
I simply changed the `save_args` and removed the `load_args` in the example to make the catalog entry not throwing an error if used as is.

## Checklist

- [X] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [X] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/1977"></a>

### CODE REVIEW

**Review by merelcht — COMMENTED** [review]
Thanks for fixing this @Kastakin ! 🙂 Does that mean that the python example for the dataset is incorrect as well? If so, would you mind updating it?

**Comment by Kastakin** [comment]
Hey @merelcht!
The Python example is actually correct, it uses the `pickle-compress` backend which allows the compression of pickle files and uses the kwarg `compression` to specify the compression format to use when reading/writing the pickle file.

I assume that the catalog example was created by mimicking the Python example without considering the different kwargs required by `joblib`. 

Maybe it would be a good idea to have a coherent exaample for both the Python and catalog cases? If that's the case I'm fine with adding it to the PR!
As on which of the two adopt I would advocate for the `joblib` one due to the fact its already a requirement for other commonly used ML packages (such as `sklearn`). Its API is also a lot similar to vanilla `pickle`.

**Review by merelcht — APPROVED** [review]
Thanks for clarifying that the python example does work 🙂 I think it's fine to have slightly different examples for `yaml` and `python`, that way people who read through both can see the different options. 

I noticed the DCO check is failing, you can resolve it by following the instructions when you click on it. More info on this check: https://kedro.readthedocs.io/en/stable/contribution/developer_contributor_guidelines.html#developer-certificate-of-origin

**Review by ankatiyar — APPROVED** [review]
Thanks @Kastakin for fixing this! 😁

**Comment by Kastakin** [comment]
> Thanks for clarifying that the python example does work slightly_smiling_face I think it's fine to have slightly different examples for `yaml` and `python`, that way people who read through both can see the different options.
> 
> I noticed the DCO check is failing, you can resolve it by following the instructions when you click on it. More info on this check: https://kedro.readthedocs.io/en/stable/contribution/developer_contributor_guidelines.html#developer-certificate-of-origin

Whoops! I'm really sorry! I was sure I had signed it!
Pardon my inexperience!

**Comment by merelcht** [comment]
> Whoops! I'm really sorry! I was sure I had signed it! It should be fixed now. Pardon my inexperience!

No worries at all! Thank you so much for your contribution. Hopefully we'll see you back on our github again soon ⭐

**Pull request merged**
