### PR TITLE
Resolve inconsistencies in Spaceflights data

### PR DESCRIPTION
**Pull request by laizaparizotto**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description
This PR was created in order to #fix3110 https://github.com/kedro-org/kedro/issues/3110

> - When merging `rated_shuttles` with `companies`, both dataframes have an `id` column, and this creates `id_x` and `id_y`, which could be avoided by selectively dropping `id` before merging
> - `companies` has duplicate rows, so when merging `rated_shuttles` with `companies`, some rows are repeated and this might distort the result, which could be avoided by doing a `.drop_duplicates()` on companies

I proposed exactly what is in the description of @astrojuanlu 

## Development notes
- Changes at `kedro/docs/source/tutorial/create_a_pipeline.md` `def create_model_input_table`
- `rated_shuttles = rated_shuttles.drop('id', axis=1)` after merging `rated_shuttles` and `review`.
- `companies = companies.drop_duplicates()` before merging `rated_shuttles` and `companies`.
- Make test done and passed

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [x] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by laizaparizotto** [comment]
@ankatiyar is there anything wrong here? Not sure why tests are not successful.

**Comment by ankatiyar** [comment]
> @ankatiyar is there anything wrong here? Not sure why tests are not successful.

@laizaparizotto No, the failures are not related to your changes, just fixed it on main today, merging the main branch to your branch should fix it! :) 

I'll review this PR tomorrow!

**Comment by ankatiyar** [comment]
@laizaparizotto This looks good but I believe these are just documentation changes and we need to also change the spaceflights starters over at https://github.com/kedro-org/kedro-starters (is that right @astrojuanlu?). Would you be up for making those changes too first before we update the documentation?

**Comment by astrojuanlu** [comment]
That's correct @ankatiyar , this should come with a PR on kedro-starters first 🙏🏽 Thanks @laizaparizotto !

**Comment by laizaparizotto** [comment]
All right, I will open the PR there first then.

I saw there are two parts of the repop `kedro-starters` that include this code:

- https://github.com/kedro-org/kedro-starters/blob/0c565235b1c72286933df87690d1b90a1a05dc4e/spaceflights/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package%20%7D%7D/pipelines/data_processing/nodes.py#L62

- https://github.com/kedro-org/kedro-starters/blob/0c565235b1c72286933df87690d1b90a1a05dc4e/spaceflights-pandas-viz/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package%20%7D%7D/pipelines/data_processing/nodes.py#L64

Should I perform the changes in both?

**Comment by astrojuanlu** [comment]
> Should I perform the changes in both?

Yes! And you can keep this PR open in the meantime

**Review by AhdraMeraliQB — APPROVED** [review]
Thank you for resolving this! ⭐

**Review by ankatiyar — APPROVED** [review]
Thank you @laizaparizotto!

**Pull request merged**
