### PR TITLE
Make credentials loading consistent between `KedroContext._get_catalog()` and catalog CLI

### PR DESCRIPTION
**Pull request by MigQ2**
## Description
I found that credentials initialization is done differently in different cases:

- In [KedroContext._get_catalog()](https://github.com/kedro-org/kedro/blob/main/kedro/framework/context/context.py#L232) the [_get_config_credentials()](https://github.com/kedro-org/kedro/blob/main/kedro/framework/context/context.py#L283) method is used to grab credentials for the DataCatalog
- In [catalog CLI's `resolve_patterns()`](https://github.com/kedro-org/kedro/blob/7e02653d755a6534f158d11dcf8c5aa9db9e2a26/kedro/framework/cli/catalog.py#L230), it is done with `context.config_loader.get("credentials", None)` instead 

Is there a good reason for this? If not, I think it's better to load the credentials in a consistent way and using the same methods everywhere

## Why is this important?

I have a custom catalog class that extends `KedroCatalog` and overrides the `_get_config_credentials()` method because I get my credentials from a cloud secret management service instead of a local `credentials.yml` file. 

This was making the command `kedro catalog resolve` fail because my credentials are not in the `ConfigLoader`

## Checklist

- [X] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [X] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [X] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [X] Updated the documentation to reflect the code changes
- [X] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [X] Added tests to cover my changes (I didn't add tests as I'm not adding new functionality and I believe this should be covered by existing tests)
- [X] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by ElenaKhaustova** [comment]
Thank you, @MigQ2! This change makes sense to me. Could you please resolve the conflicts and I'll be able to approve the PR?

**Comment by MigQ2** [comment]
Hi @ElenaKhaustova, conflicts solved!

**Review by ElenaKhaustova — APPROVED** [review]
LGTM, thank you @MigQ2! ✨

**Review by merelcht — APPROVED** [review]
Thanks for the contribution @MigQ2 ! ⭐

**Pull request merged**
