### PR TITLE
Update add_another_pipeline.md

### PR DESCRIPTION
**Pull request by eduardoconto**
Remove some spurious text.

> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description
Minor update in docs.

## Development notes
Minor update in docs.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by astrojuanlu — APPROVED** [review]
Woops, good catch @eduardoconto, thank you! Could you signoff the commit to make the DCO check happy? You'll have to amend & force push.

**Review by stichbury — APPROVED** [review]
Nice spot, thanks @eduardoconto 🏆

**Comment by eduardoconto** [comment]
I created the commit with GitHub web IDE. Can we do without the signing off? It does show up as 'verified' already.

image

**Comment by astrojuanlu** [comment]
@eduardoconto I know it's annoying, especially for a one line change, but Kedro requires this. You can read the differences between "signed commits" and "signoff commits" here https://probot.github.io/apps/dco/

**Pull request merged**
