### PR TITLE
`OmegaConfigLoader` should not show `MissingConfigException` when the file is empty

### LINKED ISSUE #2566: `OmegaConfigLoader` should not throw `MissingConfigException` when the file is empty
## Description
Related #2556 

Currently, if you have an empty configuration file with `OmegaConfigLoader`, you will get this error which isn't very accurate. 

This draft PR is just a starting point, it's expected to be picked up by someone and worked on it further.
https://github.com/kedro-org/kedro/blob/653145771fa440a46b36d2c96c57a5997613da5e/kedro/config/omegaconf_config.py#L195-L200

This is due to the fact that we always return an empty dictionary when we load the configuration. In other words, we cannot distinguish between an empty file and a missing file.
https://github.com/kedro-org/kedro/blob/653145771fa440a46b36d2c96c57a5997613da5e/kedro/config/omegaconf_config.py#L274-L275
We should take this as an opportunity to refactor and simplify these conditions. Bottom line we should have a better error message to handle empty configuration properly.

## Context
How has this bug affected you? What were you trying to accomplish?
I was confused with the error because I have the config file. Initially I thought my configuration is not in the right place or I didn't config the `config_patterns` properly. The config file is actually read but the error is confusing.

## Expected Result
Tell us what should happen.
It should return an empty dictionary `{}` instead of getting error.
## Actual Result
Tell us what happens instead.
`MissingConfigException` is thrown.

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

### PR DESCRIPTION
**Pull request by ankatiyar**
Resolves #2566 

## Development notes

When config files exist but are empty, OmegaConfigLoader should not throw `MissingConfigException` but pass on an empty dict. 
Solved this in a similar way to how it's handled in `ConfigLoader` -> throw `MissingConfigException` when `processed_files` which is a set of files read for a given type of config is empty. In cases where the file exists but is empty, empty dict `{}` is returned without an error. 

As opposed to `ConfigLoader` where the config for base and runtime envs is loaded in the same function call (`ConfigLoader.get()`-> `_get_config_from_patterns()`), `OmegaConfigLoader` calls `load_and_merge_dir_config()` twice for base and runtime env, I've declared `processed_files` outside and passed it as a parameter to `load_and_merge_dir_config` and kept the logic where we raise the exception outside of the function. 

Also added a unit test to `test_omega_config.py`

NOTE : 
I checked the merging logic in `load_and_merge_dir_config()` and we still need the following lines because it handles the case when no relevant config files exist for a given pattern + env. `aggregate_config` is `dict_values([])` which `OmegaConf` complains about while merging.
https://github.com/kedro-org/kedro/blob/16d8a7559573f331680fef13ad27e484e51764f6/kedro/config/omegaconf_config.py#L278-L279
## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by noklam — APPROVED** [review]
LGTM!

**Review by merelcht — APPROVED** [review]
In general I would discourage modifying input in the way `processed_files` is here, because it makes debugging very difficult. But I can't think of an elegant way to not do it here, so I'm okay merging it as is 🙂

**Comment by noklam** [comment]
Agree with @merelcht here. The alternative would be making the `load_and_merge_dir_config` return a `Dict | None`, then we need to do some checking. It doesn't require an extra variable but one more condition to check.

I thought we are doing this for other config loaders so I am not against this implementation. The `processed_file` here doesn't do anything here or am I crazy?

https://github.com/kedro-org/kedro/blob/16d8a7559573f331680fef13ad27e484e51764f6/kedro/config/common.py#L69-L80


https://github.com/kedro-org/kedro/blob/16d8a7559573f331680fef13ad27e484e51764f6/kedro/config/common.py#L190-L206

**Comment by noklam** [comment]
Note: We should try to break down the function, it's a huge function that build path, load config, and merge

**Pull request merged**
