### PR TITLE
Add line about Viz to PR template

### PR DESCRIPTION
**Pull request by tynandebold**
## Description

Sometimes changes in Kedro impact Kedro-Viz and we're late to notice. Adding one line to the PR checklist that hopefully prompts us to think about what the impact to Viz might be.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by merelcht — APPROVED** [review]
Good call! 👍

**Comment by noklam** [comment]
Good shout, but I am not sure what does that mean to our open source contributors.

**Comment by tynandebold** [comment]
> Good shout, but I am not sure what does that mean to our open source contributors. Should it be more generic how it would affect kedro plugins downstream?

I don't think they need to worry, nor do I think it would dissuade them from opening a PR.

**Comment by deepyaman** [comment]
As the perpetrator of some recent changes that affected Viz--how do you necessarily know it will affect Viz? E.g. not on this repo even, but on Kedro-Datasets, I honestly had no idea Viz would be eagerly loading.

I have limited context, so can you think of cases where an extra reminder about Viz specifically would have avoided breaking changes? I feel like, generally, team members already would flag it if they thought it would affect Viz.

Furthermore, I agree this has limited meaning for broader contributor set. In the end, somebody from the core team who is reviewing should also think through potential effects on Viz.

**Review by astrojuanlu — APPROVED** [review]
I think it's good to have awareness of Viz as arguably the most important plugin, thanks @tynandebold !

**Pull request merged**
