### PR TITLE
 Deprecate dataset errors with module `__getattr__`, take 2

### PR DESCRIPTION
**Pull request by astrojuanlu**
## Description
Linearized version of gh-2673, see there for discussion.

Closes gh-2673.

## Development notes
The final state is exactly the same as in gh-2673. I tried to preserve the history as much as possible (possibly useless, since this is going to be squashed upon merge, but anyway). However, rebasing this was hugely painful and frankly I was not very careful with the various `s` vs `S`, because there are lots of intermediate commits that undo or revert part of the changes etc.

This is probably missing a CHANGELOG entry too.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [x] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by deepyaman** [comment]
> The final state is exactly the same as in https://github.com/kedro-org/kedro/pull/2673. I tried to preserve the history as much as possible (possibly useless, since this is going to be squashed upon merge, but anyway).

Not sure what the benefit of this is, because, as you say, final state will be the exact same. :) I don't think the particular commit history (even linearized) is that useful? And if need something more useful in the commit message, it can just be done on merge of #2673.

**Comment by astrojuanlu** [comment]
Anyway, I see the DCO bot is flipping between 👍🏽 and 👎🏽 and I have no idea why or what's going on. I'm closing this PR.

**Comment by deepyaman** [comment]
> [gh-2673](https://github.com/kedro-org/kedro/pull/2673) is not mergeable, comments aren't signed-off. if retaining the history is not important, @deepyaman consider squashing everything into one commit so we go and merge either [gh-2673](https://github.com/kedro-org/kedro/pull/2673) or this one as soon as possible.

Can always just hit the "Set DCO to pass" button and it magically takes care of it. :D

**Comment by noklam** [comment]
@deepyaman 🤫🤫

**Pull request closed without merging**
