### PR TITLE
Trigger only docs build when release notes updated

### PR DESCRIPTION
**Pull request by merelcht**
## Description
While working on https://github.com/kedro-org/kedro/pull/2887 I noticed that when I updated the release notes all code build were triggered even though the only changes in that PR are to the docs an release notes. 

I added an extra path filter to the Github actions to only run the docs build when `.md` files are updated. 

## Development notes
I tested this by branching of this branch and triggering a GA build for this branch temporarily (https://github.com/kedro-org/kedro/pull/2908). There might be a better way to do this though? @ankatiyar / @SajidAlamQB 

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by SajidAlamQB — APPROVED** [review]
Approach is perfect! Thank you! 👍

**Review by ankatiyar — APPROVED** [review]
💯

**Comment by merelcht** [comment]
> If just the release notes are updated, not even the docs need to be rebuilt as they're not included in the RTD publication.

That's a good point. @SajidAlamQB / @ankatiyar do you know if it's possible to not trigger any builds when `RELEASE.md` is updated? I initially tried to add that to the paths filtering, but since `RELEASE.md` isn't a path that didn't work.

**Comment by SajidAlamQB** [comment]
> > If just the release notes are updated, not even the docs need to be rebuilt as they're not included in the RTD publication.
> 
> That's a good point. @SajidAlamQB / @ankatiyar do you know if it's possible to not trigger any builds when `RELEASE.md` is updated? I initially tried to add that to the paths filtering, but since `RELEASE.md` isn't a path that didn't work.

hmm the `paths-ignore` filter should work to exclude specific files from triggering the workflow.

**Comment by ankatiyar** [comment]
The readthedocs build is not on Actions right now it's just the unit/lint/e2e tests. To not trigger the readthedocs build, I think maybe some repo settings need to be changed?

**Comment by merelcht** [comment]
> The readthedocs build is not on Actions right now it's just the unit/lint/e2e tests. To not trigger the readthedocs build, I think maybe some repo settings need to be changed?

I'll check if I can change it on the repo level. But in that case I'll still merge these changes as well because it does reduce the number of builds for a release notes update.

**Pull request merged**
