### PR TITLE
Update vale linter to run for all changes as a PR check

### PR DESCRIPTION
**Pull request by ankatiyar**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Development notes

* Instead of adding review comments, it will show errors on the files changed panel for a PR https://github.com/reviewdog/reviewdog#reporter-github-checks--reportergithub-pr-check
* Can also manually trigger if needed
* Exclude it from merge gatekeeper as it will now fail if there's any errors left (even if they are unnecessary changes)
* Added some extra things to the ignore list for spell checks
## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by stichbury — APPROVED** [review]

**Comment by stichbury** [comment]
Looks good to me, thanks @ankatiyar!

**Review by astrojuanlu — APPROVED** [review]
LGTM! I'm hoping that the (seemingly unrelated) test failures were transient...

```
ERROR: No matching distribution found for setuptools
```

**Comment by stichbury** [comment]
@ankatiyar Any idea why this one is still failing? I tried to re-run this morning to get it merged.

**Comment by ankatiyar** [comment]
> @ankatiyar Any idea why this one is still failing? I tried to re-run this morning to get it merged.

@stichbury The e2e tests broke yesterday (not related to this). 😞

**Pull request merged**
