### PR TITLE
Consistently write "PySpark" rather than "Pyspark"

### PR DESCRIPTION
**Pull request by deepyaman**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Development notes

Interdependent: https://github.com/kedro-org/kedro-starters/pull/179

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by deepyaman** [comment]
> Yes!
> 
> But we probably need to apply this across the board for all Kedro docs and datasets/starters/etc as I imagine it's widespread.

I actually didn't find any other instances in the repo, even though I did just notice during the morning's add-ons presentation. It may be the case in some of the other repos.

**Comment by deepyaman** [comment]
> Yes!
> 
> But we probably need to apply this across the board for all Kedro docs and datasets/starters/etc as I imagine it's widespread.

Actually, good point; I think https://github.com/kedro-org/kedro-starters/pull/179 is necessary for this to work. I also made a change in datasets, although there's no dependency there.

**Comment by merelcht** [comment]
I don't know if it makes sense to merge this before [#3228](https://github.com/kedro-org/kedro/pull/3228). IMO this is kind of part of the design review tracked in https://github.com/kedro-org/kedro/issues/3054

**Comment by deepyaman** [comment]
> I don't know if it makes sense to merge this before [#3228](https://github.com/kedro-org/kedro/pull/3228). IMO this is kind of part of the design review tracked in #3054

Whatever works; I'm not entwined in this work, and just raised it based on what I noticed yesterday, so feel free to merge whenever it makes sense.

**Comment by stichbury** [comment]
This can be merged now I think, right @AhdraMeraliQB @deepyaman ?

**Review by DimedS — APPROVED** [review]

**Pull request merged**
