### PR TITLE
skip tests on macos because `multiprocess` default switch to `spawn` since Python 3.8

### LINKED ISSUE #3702: Test fails after following contribution guide and install dependencies in a fresh environment.
## Description

image

Test fails after fresh installation

## Context

This impact the contributing process as it adds burden on the contributor side to fix something that they didn't caused or confusing anyway.

Few observations:
- I notice test are mostly marked as @SKIP_ON_WINDOWS, it's possible we should skip it on Mac too (unsure why yet)
- Tests pass on CI 
- Suspect unknown test dependencies

## Steps to Reproduce
1. Create new environment
2. `make install-test-requirements` and `make test`

## Expected Result

Test should pass
## Actual Result

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.19.3 (main)
* Python version used (`python -V`): 3.10
* Operating system and version: MacOS

### PR DESCRIPTION
**Pull request by noklam**
## Description

Fix #3702 
## Development notes

After long investigation, I found that the issue is closely related to #3704. This wasn't a problem because in older version, MacOS was default with "fork" process until Python 3.8.

This is not ideal as there are no way to run these tests locally as most core team member is using MacOS, alternative is debug this on GitPod as a temporary solution. However, there are no way to make these tests work unless there is a clever way to make mocking work with multi-process. I spend an hour trying and cannot find anything, so I stopped here until we prioritise this. 

image

Tests passed as expected because I simply skip the test now.

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by ElenaKhaustova** [comment]
Tested on my side (MacOS):

- tests skipped as expected;
- one test is failing now: `XFAIL tests/config/test_omegaconf_config.py::TestOmegaConfigLoader::test_overlapping_patterns - Logic failing` but that's expected, right?

**Comment by noklam** [comment]
@ElenaKhaustova That's expected and not caused by this PR, I think @AhdraMeraliQB has a PR on it.
- #3696

**Review by merelcht — COMMENTED** [review]
🥲 So does this actually mean that the parallel runner is broken?

**Comment by ElenaKhaustova** [comment]
> @ElenaKhaustova That's expected and not caused by this PR, I think @AhdraMeraliQB has a PR on it.
> 
> * [Update broken OmegaConfigLoader test  #3696](https://github.com/kedro-org/kedro/pull/3696)
> 
> tagging @merelcht to review this since we deal with the multiprocessing thing recently.

I do not think I had it before - just checked that it came with recent `main` updates, not the current one.

**Review by merelcht — APPROVED** [review]

**Comment by noklam** [comment]
We had a discussion and it's properly best to start with fixing https://github.com/kedro-org/kedro-viz/issues/1801. The problem is not Kedro specific, but rather "thread"/"process" safety in Python. 

There are idea to provide some same hook class (or like AbstractDataset), it's unclear how it would look like so we will tackle the viz one as an example and see how it goes.

On the other hand, `kedro run --runner *****` shows up on HEAP but the number is not significant, I dump a question in Slack to see if there are anyone using it, or is there a good reason not to use it.

**Review by ElenaKhaustova — APPROVED** [review]

**Pull request merged**
