### PR TITLE
More tidying work for starters

### PR DESCRIPTION
**Pull request by noklam**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description

Minor clean up. I am experimenting with smaller refactor PR to make it less destructive and easier to review. This is part of https://github.com/kedro-org/kedro/pull/3266, which is now blocked by a cookiecutter bug that probably won't get fixed in short term.

I found it tricky to debug as the  `extra_context` or `config`  has different name and get mutated implicitly and pass around. This PR only contains structure changes.

See [commits](https://github.com/kedro-org/kedro/pull/3298/commits)
1. I move the mutation logic to `_make_cookiecutter_args`, `_get_extra_context` should not mutate the context.
2. rename `selected_addons`, this tricks me as there are two types of addons, one is the flag `lint,docs,test`, the other is the interactive prompt. 

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by DimedS — COMMENTED** [review]
Nok, thank you for the PR. I also found the duality in `selected_addons` confusing. However, regarding the split of code between `_make_cookiecutter_args` and `_get_extra_context`, the purpose of each function still seems a bit unclear. Initially, I assumed `_get_extra_context` was meant to generate a fully-prepared dictionary for use in `_make_cookiecutter_args`, but it appears there are still some modifications being made. In my opinion, it would be more effective to shift all modifications to `_get_extra_context`. This way, we can ensure it produces a completely ready config, aligning with its docstring description: “Generates a config dictionary that will be passed to cookiecutter as extra_context, based on CLI flags, user prompts, or a configuration file."

**Comment by noklam** [comment]
@DimedS Thanks! I like the idea

**Review by DimedS — APPROVED** [review]
Thanks @noklam , looks good to me!

**Review by SajidAlamQB — APPROVED** [review]
Thank you!

**Comment by noklam** [comment]
@astrojuanlu I have no clue about the rtd error, any idea?

**Comment by astrojuanlu** [comment]
```
b'\nTimeoutError: Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!\n    at ChromeLauncher.launch (file:///home/docs/.asdf/installs/nodejs/19.0.1/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:119:23)\n    at async run (file:///home/docs/.asdf/installs/nodejs/19.0.1/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:404:19)\n    at async cli (file:///home/docs/.asdf/installs/nodejs/19.0.1/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:184:3)\n\n'
```

I hope it was a temporary error when generating the Mermaid chart. Re-running.

**Review by ankatiyar — APPROVED** [review]

**Pull request merged**
