### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by HKABIG**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [x] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Thanks for this @HKABIG ! Do you intend to fix more typos? Or is this ready for review already?

Could you please signoff your commit so the DCO check passes? If you click on it you will find instructions. If it was only one commit you can do `git commit --amend --signoff --no-edit`, if you had more, `git rebase --signoff`. After rewriting the history you will need to do `git push --force`.

And if you keep working on this branch, please use the `-s/--signoff` flag when committing, for example `git commit -s -m 'Add feature'`.

**Review by stichbury — APPROVED** [review]
These LGTM thanks @HKABIG but before we can accept them, please do the DCO signoff as described. Thank you again for your contribution 🌟

**Review by astrojuanlu — APPROVED** [review]

**Comment by astrojuanlu** [comment]
Hey @HKABIG , the branch got deleted - was it accidental?

**Comment by HKABIG** [comment]
@astrojuanlu I am really sorry I unknowingly deleted the forked repo
I am trying to get back my changes using my local fork

**Comment by HKABIG** [comment]
@astrojuanlu I Created a pr at #3270

**Pull request closed without merging**
