### PR TITLE
Update docs on installing development requirements

### PR DESCRIPTION
**Pull request by ElenaKhaustova**
## Description
Solves https://github.com/kedro-org/kedro/issues/2519

Docs update following the https://github.com/kedro-org/kedro-starters/pull/238

## Development notes
We updated docs in the development section related to linting and test requirements installation.

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by astrojuanlu — COMMENTED** [review]
I like how these docs look like! But wondering if we should also update the template 

https://github.com/kedro-org/kedro/blob/6bf29f9a7f9496ebffaa6f50e5d61549d21d8e0f/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/requirements.txt#L5-L8

otherwise our docs and the result of `kedro new` would be somewhat inconsistent

**Review by ankatiyar — APPROVED** [review]
💯

**Review by astrojuanlu — APPROVED** [review]

**Comment by ElenaKhaustova** [comment]
@ankatiyar, @astrojuanlu thank you for the review!

I've added some updates after your approval as e2e and unit tests were failing. In the tests we relied on the old format of `requirements.txt` for kedro project which included development requirements. We also use a separate starter template for e2e tests which I had to update: https://github.com/kedro-org/kedro/tree/main/features/steps/test_starter

Could you please take a brief look one more time?

Also, I found using a separate starter for e2e test a bit counterintuitive as I expected the default starter from the project to be used. What do you think of updating e2e test and copying the default starter instead of keeping separate one?

**Review by ankatiyar — APPROVED** [review]
Thanks for also fixing the tests @ElenaKhaustova!

**Review by astrojuanlu — APPROVED** [review]
LGTM!

**Pull request merged**
