### PR TITLE
Update `CITATION.cff` to be the same as the TSC list in the docs

### LINKED ISSUE #3412: Update authors in CITATION.cff
## Description
Post `0.19.0` we should update the list of authors in CITATION.cff

## Context
- `CITATION.cff` contains all maintainers it should reflect who actively work on the project 
- The docs https://docs.kedro.org/en/stable/contribution/technical_steering_committee.html makes a difference between current TSC members and previous. Changes to this must be subject to a vote. 

## Implementation
Double check what the expectation is for `CITATION.cff`. Should contributors be added to this per release?

### PR DESCRIPTION
**Pull request by merelcht**
## Description
Resolves #3412 

## Development notes
As explained in #3412 there are no rules or guidelines about who should/shouldn't be mentioned as authors in a citation file. I think it's easiest to maintain this list to make authors equal to TSC members. So the list in the citation file should always be the same as https://docs.kedro.org/en/stable/contribution/technical_steering_committee.html#current-maintainers

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by stichbury** [comment]
I noticed that @astrojuanlu has an orcid ID listed but nobody else does. I think we should be consistent and list everybody's or nobody's, right?

**Review by stichbury — APPROVED** [review]
Approving the changes, thanks @merelcht 🌟

**Comment by astrojuanlu** [comment]
ORCiD is a very academic thing, I have it because I wanted to track other scientific work _in the old days_ 😅 unsure if it's worth forcing everyone to create one, but I'm not opposed of course.

**Review by astrojuanlu — APPROVED** [review]
👏🏽

**Comment by stichbury** [comment]
> ORCiD is a very academic thing, I have it because I wanted to track other scientific work _in the old days_ 😅 unsure if it's worth forcing everyone to create one, but I'm not opposed of course.

I'm aware of what it is; I have my own and would imagine there are other team members that do too. And for that reason, in the interest of consistency, I think either all TSC members should have their ID included or none. It's gone down for maintenance right now but when it comes back I'll check to see who else needs adding.

**Pull request merged**
