### PR TITLE
Update Kedro-Viz version to v5 in docs

### PR DESCRIPTION
**Pull request by tynandebold**
## Description

After the release of https://github.com/kedro-org/kedro-viz/pull/1002 we need to update our requirement here.

## Development notes

Just one line in the docs.

## Checklist

- [x] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

<a href="https://gitpod.io/#https://github.com/kedro-org/kedro/pull/1764"></a>

### CODE REVIEW

**Review by yetudada — APPROVED** [review]
You may also want to poke around with the Starters as well 🥳 And thank you for this.

**Comment by tynandebold** [comment]
Definitely. Antony flagged that to me as well.

**Review by MerelTheisenQB — APPROVED** [review]
👍

**Review by AntonyMilneQB — APPROVED** [review]
Thanks for doing this!

**Pull request merged**
