### PR TITLE
doc: fix typo return vs yield node generator

### PR DESCRIPTION
**Pull request by inigohidalgo**
> **NOTE:** Kedro datasets are moving from `kedro.extras.datasets` to a separate `kedro-datasets` package in
> [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.
## Description

Fixing a small error in new generator documentation.

A line read:
> Update the `make_prediction` function definition to use `return` instead of `yield`.

When it should be

> Update the `make_prediction` function definition to use `yield` instead of `return`.

## Checklist

NA: documentation change only

### CODE REVIEW

**Review by stichbury — APPROVED** [review]
Approve from docs PoV but I've no idea if it's correct technically.

**Comment by stichbury** [comment]
Thanks @inigohidalgo !

**Review by noklam — APPROVED** [review]
🫣Thanks for picking this up.

**Comment by AhdraMeraliQB** [comment]
Well spotted @inigohidalgo! Could you check the DCO failure by signing your commit message? https://github.com/kedro-org/kedro/pull/3023/checks?check_run_id=16616352181

**Pull request merged**
