### PR TITLE
Fix `mypy` error postitional only

### PR DESCRIPTION
**Pull request by merelcht**
## Description
Part of #2156 and follow up on #3497 and https://github.com/kedro-org/kedro/pull/3490

## Development notes
This PR specifically addresses the following error which was flagged for all CLI commands where we call `@click.pass_obj`
```
kedro/framework/cli/pipeline.py:139: error: Argument 1 to "pass_obj" has incompatible type "Callable[[ProjectMetadata, str, str, bool, KwArg(Any)], None]"; expected "Callable[[Any, str, str, bool, KwArg(Any)], None]"  [arg-type]
kedro/framework/cli/pipeline.py:139: note: This is likely because "delete_pipeline" has named arguments: "metadata". Consider marking them positional-only
```

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Comment by astrojuanlu** [comment]
```
Argument 1 to "pass_obj" has incompatible type "Callable[[ProjectMetadata, str, str, bool, KwArg(Any)], None]"; expected "Callable[[Any, str, str, bool, KwArg(Any)], None]"  [arg-type]
```

MyPy error messages always so helpful... isn't `ProjectMetadata` compatible with `Any`?

---

```
This is likely because "delete_pipeline" has named arguments: "metadata". Consider marking them positional-only
```

does this solution work to avoid adding the `# type: ignore` comments?

**Comment by merelcht** [comment]
> ```
> This is likely because "delete_pipeline" has named arguments: "metadata". Consider marking them positional-only
> ```
> 
> does this solution work to avoid adding the `# type: ignore` comments?

Ah it does! I couldn't figure out at first how to do this. The only thing I'm not 100% sure about is whether the argument `args: Any` in some of the CLI commands should be marked as positional-only as well?

**Comment by astrojuanlu** [comment]
> The only thing I'm not 100% sure about is whether the argument args: Any in some of the CLI commands should be marked as positional-only as well?

Good question 🤔 Not sure how the current `args` are being used, I'm used to see `*args` instead but not sure it makes sense in this case (and `*args` are positional-only by definition).

**Review by SajidAlamQB — APPROVED** [review]

**Review by ankatiyar — APPROVED** [review]

**Review by DimedS — APPROVED** [review]
Thanks, @merelcht , LGTM!

**Pull request merged**
