### PR TITLE
Bring back `.puml` diagrams that show entrypoint flows as mermaid diagrams

### PR DESCRIPTION
**Pull request by merelcht**
## Description
Undo https://github.com/kedro-org/kedro/pull/2563

>[!IMPORTANT]
> This PR only brings the diagrams back. I'll follow up with PRs to make the diagrams up to date with the current entrypoint flows.

Original motivation for adding these diagrams by @idanov (copied from `private-kedro`)

### Description

This PR adds a number of simplified (informal) sequence diagrams to help with the visibility on what is happening for all Kedro project entrypoints. For now the usage is internal only, but when we iron out Kedro's architecture and polish the diagrams, we might consider adding them to the official Kedro documentation to aid plugin developers in their understanding of Kedro internals.

### Development notes

There are 7 `.puml` files documenting the sequence of actions triggered by each of the following Kedro entrypoints:
- `kedro` in a folder without a Kedro project
- `kedro` in a folder with Kedro project
- `kedro ipython`
- `kedro run`
- `<package>` and `python -m <package>`
- `kedro plugin`
- Running installed Kedro project from another Python script

From these diagrams we can already see some inefficiencies how they are kickstarted, e.g. running Kedro as a package does not allow for any command arguments and it is different than `kedro run`. In the future we should aim to fix that and make both flows go through the same sequence of actions.

These diagrams can serve as a good map for redesigning and simplifying Kedro's plugin system as needed by https://github.com/quantumblacklabs/private-kedro/issues/884.

PS: For those unfamiliar with `.puml`, this is the format used by [PlantUML](https://plantuml.com/) which is an open-source tool for diagraming. There is a PlantUML PyCharm plugin and possibly one for VSCode as well.

## Developer Certificate of Origin
We need all contributions to comply with the [Developer Certificate of Origin (DCO)](https://developercertificate.org/). All commits must be signed off by including a `Signed-off-by` line in the commit message. [See our wiki for guidance](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers/).

If your PR is blocked due to unsigned commits, then you must follow the instructions under "Rebase the branch" on the GitHub Checks page for your PR. This will retroactively add the sign-off to all unsigned commits and allow the DCO check to pass.

## Checklist

- [ ] Read the [contributing](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Signed off each commit with a [Developer Certificate of Origin (DCO)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository)
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/kedro-org/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Checked if this change will affect Kedro-Viz, and if so, communicated that with the Viz team

### CODE REVIEW

**Review by noklam — APPROVED** [review]

**Comment by astrojuanlu** [comment]
My first attempt was not very promising 😅 

image

Can't we convert them to Mermaid and put them in our wiki, where the rest of our dev docs live? I tried an AI-powered assistant and it seemingly got it right the first time:

image

**Comment by merelcht** [comment]
@astrojuanlu That's a shame.. it works fine in PyCharm:

Screenshot 2024-07-16 at 16 12 00

I'm fine changing the format, but I think the benefit of having them in the repo is that they can be reviewed.

**Comment by merelcht** [comment]
@astrojuanlu I've converted all `.puml` diagrams to mermaid ones. If you're happy with how it looks, I'll remove the `.puml` diagrams and will work on bringing these all up to date in subsequent PRs.

**Comment by astrojuanlu** [comment]
I gave it a quick try and it works beautifully ✨ And the good thing is that now these could be easily embedded in our docs, wiki if needed. Go ahead!

**Review by astrojuanlu — APPROVED** [review]

**Pull request merged**
